package X;

/* renamed from: X.2CD  reason: invalid class name */
public class AnonymousClass2CD {
    public static final String A00;
    public static final String A01;
    public static final String A02;
    public static final String A03;
    public static final String A04;
    public static final String A05;
    public static final String A06;
    public static final String A07;
    public static final String A08;
    @Deprecated
    public static final String A09;
    public static final String A0A;
    @Deprecated
    public static final String A0B;
    @Deprecated
    public static final String A0C;

    static {
        StringBuilder A0o = AnonymousClass001.A0o();
        A0o.append("SELECT ");
        String str = AnonymousClass2C5.A01;
        String A10 = AnonymousClass0x9.A10(str, A0o);
        A0o.append("message_view");
        A0o.append(" WHERE ");
        A0o.append("sort_id");
        A0o.append(" IN (SELECT docid FROM ");
        A0o.append("message_ftsv2");
        A0o.append(" AS ");
        A0o.append("message_ftsv2");
        A0o.append(", ");
        A0o.append("available_message_view");
        A0o.append(" AS message  WHERE ");
        A0o.append("message_ftsv2");
        A0o.append(" MATCH ? AND ");
        A0o.append("message_ftsv2.docid = message.sort_id) ");
        A0o.append(" ORDER BY ");
        A0o.append("sort_id");
        A03 = AnonymousClass000.A0X(" DESC", A0o);
        StringBuilder A0o2 = AnonymousClass001.A0o();
        AnonymousClass001.A1K("SELECT ", str, ", ", A0o2);
        A0o2.append("docid");
        A0o2.append(", ");
        A0o2.append("content");
        A0o2.append(", ");
        A0o2.append("fts_jid");
        A0o2.append(A10);
        A0o2.append("message_ftsv2 AS fts");
        A0o2.append(" JOIN ");
        A0o2.append("available_message_view AS message");
        A0o2.append(" WHERE ");
        String A0p = C18310x6.A0p("fts.docid = message.sort_id", A0o2);
        A0o2.append("message_ftsv2");
        A07 = AnonymousClass000.A0X(" MATCH ? ", A0o2);
        StringBuilder A0o3 = AnonymousClass001.A0o();
        C18260x0.A0p("SELECT ", str, ", ", "docid", A0o3);
        A0o3.append(", ");
        C18260x0.A0p("content", ", ", "fts_jid", A10, A0o3);
        AnonymousClass001.A1K("message_ftsv2 AS fts", " JOIN ", "available_message_view AS message", A0o3);
        C18260x0.A0p(" ON ", "fts.docid = message.sort_id", " WHERE ", "message_ftsv2", A0o3);
        A06 = AnonymousClass000.A0X(" MATCH ? ", A0o3);
        StringBuilder A0l = AnonymousClass000.A0l("SELECT ");
        C57212tH.A03("message", A0l, AnonymousClass2C5.A03);
        A0l.append(", links.link_index AS link_index FROM ");
        A0l.append("available_message_view AS message");
        A0l.append(" INNER JOIN ");
        A0l.append("message_link AS links");
        A0l.append(" ON message.");
        A0l.append("_id");
        A0l.append(" = links.");
        A0l.append("message_row_id");
        A0l.append(" WHERE message.");
        A0l.append("sort_id");
        A0l.append(" IN ");
        A0l.append("(SELECT docid FROM message_ftsv2 WHERE content MATCH ? )");
        A02 = AnonymousClass000.A0X(" ORDER BY sort_id DESC", A0l);
        StringBuilder A0B2 = C18260x0.A0B("SELECT ", str, A10, "available_message_view", " WHERE ");
        A0B2.append("sort_id");
        A0B2.append(" IN ");
        A0A = AnonymousClass000.A0V("(SELECT docid FROM message_ftsv2 AS messages_fts, message_view AS message WHERE messages_fts.content MATCH ? AND messages_fts.docid = message.sort_id AND message.starred = 1 AND (message_type != '7'))", " ORDER BY sort_id DESC", A0B2);
        StringBuilder A0B3 = C18260x0.A0B("SELECT ", str, A10, "message_view", " WHERE ");
        A0B3.append("_id");
        A0B3.append(" IN (SELECT docid FROM ");
        A0B3.append("messages_fts");
        A0B3.append(" AS messages_fts, ");
        A0B3.append("available_message_view");
        A0B3.append(" AS message  WHERE content MATCH ? AND messages_fts.docid = message.");
        A0B3.append("_id");
        A0B3.append(" AND message.");
        A0B3.append("message_type");
        A0B3.append(" IN ('");
        A0B3.append(9);
        A0B3.append("' , '");
        A0B3.append(26);
        A0B3.append("' ) AND ");
        C18260x0.A0p("message.chat_row_id = ?) ", " ORDER BY ", "sort_id", " DESC", A0B3);
        A00 = A0B3.toString();
        StringBuilder A0o4 = AnonymousClass001.A0o();
        AnonymousClass001.A1K("SELECT ", str, ", links.link_index AS link_index FROM ", A0o4);
        A0o4.append("message_view AS message");
        A0o4.append(", ");
        A0o4.append("(SELECT message_row_id, link_index FROM message_link AS link WHERE link.chat_row_id=? AND message_row_id IN ( SELECT docid FROM messages_fts, available_message_view AS message WHERE content MATCH ? AND messages_fts.docid = message._id)) links");
        A0o4.append(" WHERE ");
        A0o4.append("message._id = links.message_row_id ");
        A01 = AnonymousClass000.A0X(" ORDER BY _id DESC", A0o4);
        StringBuilder A0m = AnonymousClass000.A0m(str, ", ");
        A0m.append("messages_fts.docid AS docid");
        A0m.append(", ");
        String A0X = AnonymousClass000.A0X("messages_fts.content AS content", A0m);
        StringBuilder A0o5 = AnonymousClass001.A0o();
        AnonymousClass001.A1K("SELECT ", A0X, A10, A0o5);
        A0o5.append("message_view AS message JOIN messages_fts AS messages_fts ON messages_fts.docid = message.sort_id");
        A05 = AnonymousClass000.A0X(" WHERE content MATCH ?", A0o5);
        StringBuilder A0o6 = AnonymousClass001.A0o();
        AnonymousClass001.A1K("SELECT ", A0X, A10, A0o6);
        A0o6.append("available_message_view AS message JOIN messages_fts AS messages_fts ON messages_fts.docid = message.sort_id");
        A0o6.append(" WHERE content MATCH ? AND ");
        A04 = AnonymousClass000.A0X("chat_row_id = ?", A0o6);
        StringBuilder A0B4 = C18260x0.A0B("SELECT ", str, A10, "message_view", " WHERE ");
        A0B4.append("_id");
        A0B4.append(" IN ");
        A0B = AnonymousClass000.A0V("( \n   SELECT docid \n   FROM messages_fts AS messages_fts, available_message_view AS message \n   WHERE content MATCH ? AND messages_fts.docid = message._id\n   AND message.starred = 1 AND (message_type != '7'))\n", " ORDER BY _id DESC", A0B4);
        StringBuilder A0B5 = C18260x0.A0B("SELECT ", str, A10, "message_view", " WHERE ");
        A0B5.append("sort_id");
        A0B5.append(" IN ");
        C18260x0.A0p("( \n   SELECT docid \n   FROM message_ftsv2 AS messages_fts, available_message_view AS message \n   WHERE messages_fts.content MATCH ? AND messages_fts.docid = message.sort_id\n   AND message.starred = 1   AND (message_type != '7'))\n", " ORDER BY ", "sort_id", " DESC", A0B5);
        A0C = A0B5.toString();
        StringBuilder A0B6 = C18260x0.A0B("SELECT ", str, A10, "available_message_view", " WHERE ");
        A0B6.append("_id");
        A0B6.append(" IN ");
        A09 = AnonymousClass000.A0V("(SELECT docid FROM messages_fts AS messages_fts, message_view AS message WHERE chat_row_id = ? AND messages_fts.content MATCH ? AND messages_fts.docid = message._id AND message.starred = 1 AND (message_type != '7'))", " ORDER BY _id DESC", A0B6);
        StringBuilder A0B7 = C18260x0.A0B("SELECT ", str, A10, "available_message_view AS message", " WHERE ");
        A0B7.append("sort_id");
        A0B7.append(" IN ");
        A0B7.append("(SELECT docid FROM message_ftsv2 AS messages_fts, message_view AS message WHERE messages_fts.content MATCH ? AND messages_fts.docid = message.sort_id)");
        A0B7.append(A0p);
        A0B7.append("message.keep_in_chat = 1");
        A0B7.append(A0p);
        A08 = AnonymousClass000.A0V("(message_type != '7')", " ORDER BY sort_id DESC", A0B7);
    }
}
