package X;

import com.google.android.search.verification.client.SearchActionVerificationClientService;
import java.io.Serializable;

/* renamed from: X.8L1  reason: invalid class name */
public class AnonymousClass8L1 implements Serializable {
    public static final long serialVersionUID = -4616824299921458702L;
    public long abrDurationForIntentional;
    public int adHighBwRiskConfPct = 0;
    public int adHighBwRiskConfPctOnScreen = 0;
    public int adHighBwRiskConfPctPrefetch = 0;
    public final boolean allowAbrUpToWatchableMosInLowBuffer = false;
    public final boolean allowAudioFormatsLowerThanDefault = false;
    public final boolean alwaysPlayLiveCachedData = false;
    public int androidBandwidthFallbackNumberOfSamples = -1;
    public final float audioBandwidthFractionCell = 0.0f;
    public final float audioBandwidthFractionWifi = 0.0f;
    public final int audioMaxInitialBitrate = 50000;
    public final float audioPrefetchBandwidthFraction = 0.0f;
    public double audioRiskAdjFactor = 0.0d;
    public int backgroundPrefetchHighBwRiskConfPct = 0;
    public final float bandwidthMultiplier = 1.0f;
    public float bwWeightLimitForBWEDampening = 800.0f;
    public final boolean bypassPrefetchWidthLimits = false;
    public boolean bypassWidthLimitsSponsoredVerticalVideos = true;
    public final boolean bypassWidthLimitsStories = false;
    public final boolean bypassWidthLimitsStoriesPrefetch = false;
    public int defaultBwRiskConfPct = 50;
    public boolean disableLiveDefaultDataSourceBwSamples = false;
    public final float dropRenderFrameRatioForPreventAbrUp = 1.0f;
    public boolean enableAndroidAPIBitrate = false;
    public final boolean enableAudioAbrEvaluator = false;
    public final boolean enableAudioAbrPairing = false;
    public final boolean enableAudioAbrSecondPhaseEvaluation = false;
    public boolean enableAudioBandwidthSamples = false;
    public final boolean enableAudioIbrCache = false;
    public final boolean enableAudioIbrEvaluator = false;
    public final boolean enableAvoidOnCellular = false;
    public boolean enableBsrV2Definition = false;
    public final boolean enableBufferBasedAudioAbrEvaluation = false;
    public final boolean enableBwOnlyEstimationForLongPoll = false;
    public final boolean enableCdnBandwidthRestriction = false;
    public boolean enableConfRiskBwCache = false;
    public boolean enableDelayedPrefetchQualitySelection = false;
    public boolean enableInitialBWStdDevFix = false;
    public final boolean enableInitialBitrateBoosterByNetworkQuality = false;
    public boolean enableMosOverride;
    public boolean enableMosOverrideLive;
    public final boolean enableMultiAudioSupport = false;
    public final boolean enableSegmentBitrate = false;
    public boolean enableSmartCacheOverride;
    public boolean enableSmartCacheOverrideOnlyWhenHighMos;
    public boolean enableSmartCacheOverrideOnlyWhenHighMosForPrefetch;
    public boolean enableSmartCachePrefetchOverride;
    public final boolean enableTtfbOnlyEstimation = false;
    public final boolean enableVodPrefetchQSFix = false;
    public boolean enableXPlatBweParity = false;
    public final boolean forceCurrentNoWatchableFormatFrameDrop = true;
    public final boolean forceUpdateFormatListIfFormatSizeChanged = false;
    public int foregroundPrefetchHighBwRiskConfPct = 0;
    public final float frameDropFactor = 1.0f;
    public final boolean hashUrlForUnique = false;
    public final int highBufferBandwidthConfidencePct = 65;
    public int highBwRiskConfPct = 75;
    public double highOrBetterMosThreshold = 0.0d;
    public boolean honorDefaultBandwidthSR = false;
    public final int igClipsMinWatchableMos = 0;
    public final int initSegmentBandwidthExclusionLimitBytes = 0;
    public final float initialBitrateBoosterByNetworkQuality = 1.0f;
    public final long initialCachedBwSizeBytes = 0;
    public final float lambdaFallingBufferConfidenceCalculator = 1.0f;
    public final float lambdaRisingBufferConfidenceCalculator = 1.0f;
    public final int latencyBasedTargetBufferDrainDurationMs = 0;
    public final int latencyBasedTargetBufferSizeMs = 3000;
    public final int liveAbrDefaultMaxWidthCell = 0;
    public final int liveAbrDefaultMaxWidthWifi = 0;
    public long liveAbrDurationForIntentional;
    public final int liveAbrLatencyBasedAbrTargetBufferSizeMs = 3000;
    public final float liveAbrPrefetchLongQueueBandwidthFraction = 0.25f;
    public final int liveAbrPrefetchLongQueueSizeThreshold = 1;
    public final float liveAbrPrefetchShortQueueBandwidthFraction = 0.5f;
    public final boolean liveAllowAbrUpToWatchableMosInLowBuffer = false;
    public final boolean liveAllowAudioFormatsLowerThanDefault = false;
    public final long liveAocDefaultLimitIntentionalKbps = 0;
    public final long liveAocDefaultLimitUnintentionalKbps = 0;
    public final float liveAudioBandwidthFractionCell = 0.01f;
    public final float liveAudioBandwidthFractionWifi = 0.01f;
    public final int liveAudioMaxInitialBitrate = 50000;
    public final float liveAudioPrefetchBandwidthFraction = 0.01f;
    public double liveAudioRiskAdjFactor = 0.0d;
    public final boolean liveAvoidUseDefault = false;
    public int liveDefaultBwRiskConfPct = 50;
    public final boolean liveEnableAudioIbrCache = false;
    public final boolean liveEnableAudioIbrEvaluator = false;
    public final boolean liveEnableInitialBitrateBoosterByNetworkQuality = false;
    public final float liveExtraBandwidthFractionForQualityIncrease = 0.9f;
    public final int liveHighBufferBandwidthConfidencePct = 60;
    public int liveHighBwRiskConfPct = 75;
    public int liveHighBwRiskConfPctUltraLowLatency = 75;
    public final int liveInitialBitrate = 50000;
    public final float liveInitialBitrateBoosterByNetworkQuality = 1.0f;
    public double liveLSBVirtualBufferPercent = 0.0d;
    public final float liveLambdaFallingBufferConfidenceCalculator = 1.0f;
    public final float liveLambdaRisingBufferConfidenceCalculator = 1.0f;
    public final int liveLowBufferBandwidthConfidencePct = 85;
    public final float liveMainProcessBitrateEstimateMultiplier = 0.6f;
    public double liveMaxAlphaLowPassEMABwDown;
    public double liveMaxAlphaLowPassEMABwUp;
    public double liveMaxAlphaLowPassEMABwVol;
    public double liveMaxAlphaLowPassEMATtfbDown;
    public double liveMaxAlphaLowPassEMATtfbUp;
    public double liveMaxAlphaLowPassEMATtfbVol;
    public final float liveMaxBandwidthMultiplier = 2.0f;
    public final int liveMaxBufferedDurationMsFallingBuffer = 25000;
    public final int liveMaxDurationForQualityDecreaseMs = 25000;
    public final float liveMaxTTFBMultiplier = 3.0f;
    public final int liveMaxWidthCell = 720;
    public final int liveMaxWidthInlinePlayer = 1000;
    public final int liveMaxWidthToPrefetchCell = 396;
    public final int liveMaxWidthToPrefetchWifi = 504;
    public final float liveMinBandwidthMultiplier = 0.3f;
    public final int liveMinDurationForHighBWQualityIncreaseMs = -1;
    public final int liveMinDurationForQualityIncreaseMs = 5000;
    public final float liveMinTTFBMultiplier = 0.5f;
    public int livePersonalizedBWRiskConfPctAggressive = 70;
    public int livePersonalizedBWRiskConfPctConservative = 80;
    public int livePersonalizedBWRiskConfPctNormal = 75;
    public int livePersonalizedBWRiskConfPctVeryAggressive = 65;
    public int livePersonalizedBWRiskConfPctVeryConservative = 85;
    public double livePersonalizedRiskMultiplierAggressive = 1.0d;
    public double livePersonalizedRiskMultiplierConservative = 1.0d;
    public double livePersonalizedRiskMultiplierVeryAggressive = 1.0d;
    public double livePersonalizedRiskMultiplierVeryConservative = 1.0d;
    public double livePersonalizedVirtualBufferPercent = 0.0d;
    public final int livePredictiveABRDownBufferLLMs = 0;
    public final int livePredictiveABRDownBufferMs = 0;
    public final int livePredictiveABRMaxSingleCycleDepletionLLMs = 0;
    public final int livePredictiveABRMaxSingleCycleDepletionMs = 0;
    public final boolean livePredictiveABROnStdLive = false;
    public final float livePredictiveABRTtfbRatio = 0.0f;
    public final int livePredictiveABRUpBufferLLMs = 0;
    public final int livePredictiveABRUpBufferMs = 0;
    public final boolean livePredictiveABRUpOnLiveHead = false;
    public final int livePredictiveABRUpRetryIntervalLLMs = 0;
    public final int livePredictiveABRUpRetryIntervalMs = 0;
    public final float livePrefetchDurationMultiplier = 2.0f;
    public final int livePrefetchLongQueueBandwidthConfidencePct = -1;
    public final int livePrefetchShortQueueBandwidthConfidencePct = -1;
    public double liveRiskAdjFactor = 0.0d;
    public int liveRiskRewardRatioBufferLimitMs;
    public float liveRiskRewardRatioLowerBound;
    public float liveRiskRewardRatioUpperBound;
    public final float liveScreenWidthMultiplierLandscapeVideo = 1.2f;
    public final float liveScreenWidthMultiplierPortraitVideo = 1.2f;
    public boolean liveSelectIntermediateFormatRiskRewardBased;
    public final boolean liveShouldAvoidOnCellular = false;
    public final boolean liveShouldFilterHardwareCapabilities = false;
    public boolean liveShouldUseLowPassEMAAsymmetryForBWEstimation;
    public boolean liveShouldUseLowPassEMAForBWEstimation;
    public boolean liveShouldUseLowPassWithWeightedEMAForBWEstimation;
    public final int liveStoriesMaxBufferedDurationMsFallingBuffer = 25000;
    public final int liveStoriesMinDurationForHighBWQualityIncreaseMs = -1;
    public double liveSystemicRiskAudioBitrateBoostFactor = 1.0d;
    public boolean liveSystemicRiskAudioEnable = false;
    public boolean liveSystemicRiskAudioEnableABR = false;
    public boolean liveSystemicRiskAudioEnableDynOtherBitrate = false;
    public double liveSystemicRiskAudioFactor = 2.0d;
    public double liveSystemicRiskAudioLowMosFactor = 1.2d;
    public int liveSystemicRiskAudioOtherBitrate = 0;
    public int liveSystemicRiskAvgSegmentDurationMs = 2000;
    public boolean liveSystemicRiskEnable = false;
    public double liveSystemicRiskFactor = 2.0d;
    public double liveSystemicRiskLowMosFactor = 1.2d;
    public int liveSystemicRiskMaxLookaheadDurationMs = 0;
    public final boolean liveTreatCurrentNullAsLowBuffer = false;
    public double liveULSBVirtualBufferPercent = 0.0d;
    public boolean liveUpdateFormatsWithIntentionChange;
    public boolean liveUseMaxBitrateForABRIfLower;
    public boolean liveUseMaxBitrateForAOCIfLower;
    public boolean liveUsePersonalizedBWRiskConfPcts;
    public boolean liveUsePersonalizedRiskMultipliers;
    public boolean liveUsePersonalizedVirtualBuffer;
    public boolean liveUseRiskRewardRatio;
    public double liveUserLowLatencyRiskAdjFactor = 0.0d;
    public double liveUserLowLatencySystemicRiskFactor = 0.0d;
    public double liveUserUltraLowLatencyRiskAdjFactor = 0.0d;
    public double liveUserUltraLowLatencySystemicRiskFactor = 0.0d;
    public double liveVirtualBufferPercent = 0.0d;
    public final int lowBufferBandwidthConfidencePct = 90;
    public final float mainProcessBitrateEstimateMultiplier = 0.6f;
    public double maxAlphaLowPassEMABwDown;
    public double maxAlphaLowPassEMABwUp;
    public double maxAlphaLowPassEMABwVol;
    public double maxAlphaLowPassEMATtfbDown;
    public double maxAlphaLowPassEMATtfbUp;
    public double maxAlphaLowPassEMATtfbVol;
    public final float maxBandwidthMultiplier = 2.0f;
    public final int maxBufferedDurationMsFallingBuffer = 25000;
    public final int maxDurationForQualityDecreaseMs = 25000;
    public final int maxInitialBitrate = 50000;
    public int maxNumberSmallBwSamplesIgnored = 0;
    public final float maxTTFBMultiplier = 3.0f;
    public final int maxWidthCell = 480;
    public final int maxWidthInlinePlayer = 720;
    public final int maxWidthSphericalVideo = 0;
    public final int maxWidthToPrefetchAbr = 640;
    public final int maxWidthToPrefetchAbrCell = 480;
    public final float minBandwidthMultiplier = 0.3f;
    public final int minBufferedDurationMsForMosAwareCache = 0;
    public final int minDurationForHighBWQualityIncreaseMs = -1;
    public final int minFramesDropForPreventAbrUp = 0;
    public final int minFramesRenderedForPreventAbrUp = 0;
    public final int minMosConstraintLimit = 0;
    public final int minMosForCachedQuality = 0;
    public final int minMosForPrefetch = 0;
    public double minOverallMosForABR = 0.0d;
    public final float minPartiallyCachedSpan = 1.0f;
    public final float minTTFBMultiplier = 0.5f;
    public final float minVisualQualityScore = -1.0f;
    public final int minWatchableMos = 0;
    public final float minWidthMultiplierFrameDrop = 0.0f;
    public int modBwRiskConfPct = 65;
    public double modOverallMosForABR = 0.0d;
    public final int mosDiffPctForCachedQuality = 0;
    public final float mosPrefetchFractionByNetworkQuality = 1.0f;
    public boolean overrideCacheWhenHighMos;
    public boolean overrideCacheWhenHighMosForPrefetch;
    public long personalizedAggressiveStallDuration = 120000;
    public int personalizedBWRiskConfPctAggressive = 70;
    public int personalizedBWRiskConfPctConservative = 80;
    public int personalizedBWRiskConfPctNormal = 75;
    public int personalizedBWRiskConfPctVeryAggressive = 65;
    public int personalizedBWRiskConfPctVeryConservative = 85;
    public long personalizedConservativeStallDuration = C625635p.A0L;
    public double personalizedRiskMultiplierAggressive = 1.0d;
    public double personalizedRiskMultiplierConservative = 1.0d;
    public double personalizedRiskMultiplierVeryAggressive = 1.0d;
    public double personalizedRiskMultiplierVeryConservative = 1.0d;
    public long personalizedVeryAggressiveStallDuration = 300000;
    public double personalizedVirtualBufferPercent = 0.0d;
    public final float prefetchBandwidthFraction = 0.0f;
    public final int prefetchLongQueueBandwidthConfidencePct = -1;
    public final float prefetchLongQueueBandwidthFraction = 0.5f;
    public final int prefetchLongQueueSizeThreshold = 3;
    public final int prefetchShortQueueBandwidthConfidencePct = -1;
    public final float prefetchShortQueueBandwidthFraction = 0.75f;
    public final boolean removeCDNResponseTimeForLongPoll = false;
    public double riskAdjFactor = 0.0d;
    public final int riskRewardRatioBufferLimitMs = 0;
    public final float riskRewardRatioLowerBound = 0.0f;
    public final float riskRewardRatioUpperBound = 0.0f;
    public float riskRewardRatioUpperBoundSfv;
    public final float screenWidthMultiplierLandscapeVideo = 1.2f;
    public final float screenWidthMultiplierPortraitVideo = 1.2f;
    public final boolean selectIntermediateFormatRiskRewardBased = false;
    public final boolean serverSideForwardBwe = false;
    public boolean shouldCountFirstChunkOnly = false;
    public boolean shouldDeleteNonSR = false;
    public boolean shouldDeprecateLiveInitialABR = false;
    public final boolean shouldEnableAvoidOnABR = false;
    public final boolean shouldFilterHardwareCapabilities = false;
    public boolean shouldLogInbandTelemetryBweDebugString = false;
    public boolean shouldUseFreshAbrEvaluatorPerLivePrefetch;
    public boolean shouldUseLowPassEMAAsymmetryForBWEstimation;
    public boolean shouldUseLowPassEMAForBWEstimation;
    public boolean shouldUseLowPassWithWeightedEMAForBWEstimation;
    public boolean shouldUseServerSideGoodput = false;
    public final boolean skipCachedAsCurrent = false;
    public double smartCacheOverridePrefetchThreshold = 0.0d;
    public double smartCacheOverrideThreshold = 0.0d;
    public final float softMinMosBandwidthFractionForAbrSelector = 0.0f;
    public final float softMinMosForAbrSelector = 0.0f;
    public final int ssAbrSampleMaxValidTimeAcrossVideosMs = 30000;
    public final int ssAbrSampleMaxValidTimeMs = SearchActionVerificationClientService.NOTIFICATION_ID;
    public final float storiesMaxBandwidthMultiplier = 2.0f;
    public final int storiesMaxBufferedDurationMsFallingBuffer = 25000;
    public final float storiesMaxTTFBMultiplier = 3.0f;
    public final float storiesMinBandwidthMultiplier = 0.3f;
    public final int storiesMinDurationForHighBWQualityIncreaseMs = -1;
    public final int storiesMinMosForCachedQuality = 0;
    public final float storiesMinTTFBMultiplier = 0.5f;
    public final int storiesMosDiffPctForCachedQuality = 0;
    public final int storyLatencyBasedTargetBufferSizeMs = 0;
    public double systemRiskFactorForIgClips = 0.0d;
    public double systemicRiskAudioBitrateBoostFactor = 1.0d;
    public boolean systemicRiskAudioEnable = false;
    public boolean systemicRiskAudioEnableABR = false;
    public boolean systemicRiskAudioEnableDynOtherBitrate = false;
    public double systemicRiskAudioFactor = 2.0d;
    public double systemicRiskAudioLowMosFactor = 1.2d;
    public int systemicRiskAudioOtherBitrate = 0;
    public int systemicRiskAvgSegmentDurationMs = 2000;
    public boolean systemicRiskEnable = false;
    public boolean systemicRiskEnableForPrefetch = false;
    public boolean systemicRiskEnableForStories = false;
    public double systemicRiskFactor = 2.0d;
    public double systemicRiskFactorForBgPrefetch = 0.0d;
    public double systemicRiskLowMosFactor = 1.2d;
    public double systemicRiskLowMosFactorForBgPrefetch = 0.0d;
    public double systemicRiskLowMosFactorForIgClips = 0.0d;
    public int systemicRiskMaxLookaheadDurationMs = 0;
    public double systemicRiskModMosFactor = 1.0d;
    public final boolean treatCurrentNullAsLowBuffer = false;
    public boolean treatShortFormAsStories = false;
    public int ttfbMsecWithServerSideGoodput = -1;
    public float ttfbWeightLimitForBWEDampening = 300.0f;
    public int ultraLowLatencyAdjustedLowestQualityIndex = -1;
    public boolean updateFormatsWithIntentionChange;
    public final boolean useDefaultFormatAsBackupForScreenWidthConstraints = false;
    public final boolean useLogarithmicRisk = false;
    public final boolean useMosAwareCachedSelection = false;
    public boolean useOverallMosForABR = false;
    public boolean usePersonalizedBWRiskConfPcts;
    public boolean usePersonalizedRiskMultipliers;
    public boolean usePersonalizedVirtualBuffer;
    public boolean usePlaybackCsvqm = false;
    public boolean usePlaybackMosForLowMosABR = true;
    public final boolean useRiskRewardRatio = false;
    public final boolean useSSBweForLowLatency = false;
    public final boolean useSSBweForRegularLatency = false;
    public final boolean useSSBweForUltraLowLatency = false;
    public boolean useUnifiedUploadMos = false;
    public boolean useXPlatBwe = false;
    public final int veryHighBufferDurationMsForBandwidthBoost = -1;
    public final int veryHighBufferDurationMsForBandwidthBoostIG = -1;
    public double virtualBufferPercent = 0.0d;
    public final float vodPrefetchDurationMultiplier = 2.0f;
    public double xplatAlphaBitrate = 0.1d;
    public double xplatAlphaLatency = 0.25d;
    public double xplatLowPassFilterAlphaMultiplier = 1.0d;
    public long xplatMaxNumSmallSamplesIgnored = -1;
    public long xplatSizeThreshBytes = 10000;
    public boolean xplatUseLowPassFilter = true;
    public long xplatWindowMinSamples = 10;
    public long xplatWindowSizeSeconds = 20;
}
