package X;

/* renamed from: X.9JK  reason: invalid class name */
public enum AnonymousClass9JK {
    CACHE_CHECK_START,
    CACHE_CHECK_END,
    DOWNLOAD_START,
    DOWNLOAD_END,
    DECRYPT_START,
    DECRYPT_OPERATION_START,
    DECRYPT_OPERATION_FINISH,
    DECRYPT_END,
    EXTRACT_START,
    EXTRACT_END,
    ENCODE_START,
    ENCODE_END,
    ENCODE_OPERATION_START,
    ENCODE_OPERATION_END,
    CACHE_PUT_START,
    CACHE_PUT_END
}
