package X;

import android.net.Uri;
import android.util.Log;
import com.facebook.video.heroplayer.setting.FbAutogeneratedSettings;
import java.io.File;
import java.io.IOException;
import java.util.Map;
import java.util.NavigableSet;
import java.util.concurrent.atomic.AtomicBoolean;

/* renamed from: X.0gv  reason: invalid class name and case insensitive filesystem */
public class C09890gv implements C187438xD {
    public long A00;
    public long A01;
    public long A02;
    public long A03;
    public long A04;
    public C184748sS A05;
    public C185788uF A06;
    public C187448xE A07;
    public C172488Li A08;
    public C187458xF A09;
    public AnonymousClass0Py A0A;
    public AnonymousClass0UP A0B;
    public boolean A0C;
    public boolean A0D;
    public boolean A0E = false;
    public final int A0F;
    public final int A0G;
    public final long A0H;
    public final long A0I;
    public final AnonymousClass6KJ A0J;
    public final AnonymousClass0Xd A0K;
    public final C142866xv A0L;
    public final C160777oI A0M;
    public final AnonymousClass8LG A0N;
    public final AtomicBoolean A0O;
    public final boolean A0P;
    public final boolean A0Q;
    public final boolean A0R;
    public final boolean A0S;
    public final boolean A0T;
    public final boolean A0U;
    public volatile boolean A0V;

    /* JADX INFO: finally extract failed */
    public final void A04() {
        try {
            C153827c5.A01("exo-closecurrentstream");
            A08((C186458vL) null, this.A08);
            if (this.A06 != null) {
                C187458xF r1 = this.A09;
                if (r1 != null) {
                    if (this.A0C) {
                        r1.BeW();
                    } else {
                        r1.BeX(A00(), this, true);
                    }
                }
                this.A06.close();
                this.A06 = null;
            }
            C172488Li r6 = this.A08;
            if (r6 != null && !r6.A08) {
                Object[] objArr = new Object[5];
                objArr[0] = this.A0L;
                AnonymousClass000.A1Q(objArr, 1, r6.A05);
                objArr[2] = Long.valueOf(r6.A04);
                objArr[3] = this.A0M.A05();
                objArr[4] = this.A0A.A06;
                C161157p6.A01("FbHttpCacheDataSource", "Cache data sink close stream. Type:%s, Offset:%d, FileSize:%d, Vid:%s, Key:%s", objArr);
                C184748sS r0 = this.A05;
                if (r0 != null) {
                    try {
                        r0.close();
                        this.A05 = null;
                    } catch (C140446tk unused) {
                    }
                }
            }
            C172488Li r12 = this.A08;
            if (r12 != null && !r12.A08) {
                A09(r12);
            }
            this.A08 = null;
            C153827c5.A00();
        } catch (Throwable th) {
            C172488Li r13 = this.A08;
            if (r13 != null && !r13.A08) {
                A09(r13);
            }
            this.A08 = null;
            C153827c5.A00();
            throw th;
        }
    }

    /* JADX WARNING: Code restructure failed: missing block: B:23:0x00b1, code lost:
        if (r10.A06 > 0) goto L_0x00b3;
     */
    /* Code decompiled incorrectly, please refer to instructions dump. */
    public long Bfw(X.C161387pX r30) {
        /*
            r29 = this;
            r11 = 0
            r5 = r29
            r5.A0C = r11
            r6 = r30
            java.lang.String r0 = r6.A06     // Catch:{ IOException -> 0x0126 }
            r28 = r0
            X.7oI r7 = r5.A0M     // Catch:{ IOException -> 0x0126 }
            java.lang.String r4 = r7.A05()     // Catch:{ IOException -> 0x0126 }
            android.net.Uri r0 = r6.A04     // Catch:{ IOException -> 0x0126 }
            r27 = r0
            boolean r15 = r5.A0Q     // Catch:{ IOException -> 0x0126 }
            X.8LG r3 = r5.A0N     // Catch:{ IOException -> 0x0126 }
            boolean r2 = r3.useShortKey     // Catch:{ IOException -> 0x0126 }
            boolean r17 = r7.A07()     // Catch:{ IOException -> 0x0126 }
            boolean r1 = r3.splitLastSegmentCachekey     // Catch:{ IOException -> 0x0126 }
            boolean r0 = r3.skipThumbnailCacheKey     // Catch:{ IOException -> 0x0126 }
            r18 = r1
            r19 = r0
            r16 = r2
            r13 = r28
            r14 = r4
            r12 = r27
            java.lang.String r2 = X.C161157p6.A00(r12, r13, r14, r15, r16, r17, r18, r19)     // Catch:{ IOException -> 0x0126 }
            boolean r0 = r3.checkThumbnailCache     // Catch:{ IOException -> 0x0126 }
            r12 = 1
            if (r0 == 0) goto L_0x0075
            X.0Xd r0 = r5.A0K     // Catch:{ IOException -> 0x0126 }
            X.8xH r21 = r0.A08()     // Catch:{ IOException -> 0x0126 }
            long r8 = r6.A03     // Catch:{ IOException -> 0x0126 }
            long r0 = r6.A02     // Catch:{ IOException -> 0x0126 }
            r22 = r2
            r23 = r8
            r25 = r0
            boolean r10 = r21.BH9(r22, r23, r25)     // Catch:{ IOException -> 0x0126 }
            if (r10 != 0) goto L_0x0075
            boolean r14 = r3.useShortKey     // Catch:{ IOException -> 0x0126 }
            boolean r18 = X.AnonymousClass000.A1T(r17)
            boolean r13 = r3.splitLastSegmentCachekey     // Catch:{ IOException -> 0x0126 }
            boolean r10 = r3.skipThumbnailCacheKey     // Catch:{ IOException -> 0x0126 }
            r19 = r13
            r20 = r10
            r16 = r15
            r17 = r14
            r14 = r28
            r15 = r4
            r13 = r27
            java.lang.String r22 = X.C161157p6.A00(r13, r14, r15, r16, r17, r18, r19, r20)     // Catch:{ IOException -> 0x0126 }
            r13 = 2
            long r0 = r0 / r13
            r25 = r0
            boolean r0 = r21.BH9(r22, r23, r25)     // Catch:{ IOException -> 0x0126 }
            if (r0 == 0) goto L_0x0075
            r2 = r22
        L_0x0075:
            r13 = 2
            X.0Py r0 = r5.A0A     // Catch:{ IOException -> 0x0126 }
            boolean r0 = X.AnonymousClass000.A1X(r0)
            X.C159197lM.A02(r0)     // Catch:{ IOException -> 0x0126 }
            X.0Py r0 = new X.0Py     // Catch:{ IOException -> 0x0126 }
            r0.<init>(r6, r2)     // Catch:{ IOException -> 0x0126 }
            r5.A0A = r0     // Catch:{ IOException -> 0x0126 }
            X.8Kz r0 = r3.cache     // Catch:{ IOException -> 0x0126 }
            boolean r0 = r0.enableCacheInstrumentation     // Catch:{ IOException -> 0x0126 }
            if (r0 == 0) goto L_0x00a2
            java.lang.String r0 = r27.toString()     // Catch:{ IOException -> 0x0126 }
            X.0UP r8 = new X.0UP     // Catch:{ IOException -> 0x0126 }
            r8.<init>(r7, r0)     // Catch:{ IOException -> 0x0126 }
            r5.A0B = r8     // Catch:{ IOException -> 0x0126 }
            X.0Xd r0 = r5.A0K     // Catch:{ IOException -> 0x0126 }
            X.8xH r1 = r0.A08()     // Catch:{ IOException -> 0x0126 }
            X.0Py r0 = r5.A0A     // Catch:{ IOException -> 0x0126 }
            r8.A05(r0, r1)     // Catch:{ IOException -> 0x0126 }
        L_0x00a2:
            X.7ni r10 = r6.A05     // Catch:{ IOException -> 0x0126 }
            X.8Kz r0 = r3.cache     // Catch:{ IOException -> 0x0126 }
            boolean r0 = r0.enableInitSegmentFix     // Catch:{ IOException -> 0x0126 }
            if (r0 == 0) goto L_0x00b3
            int r0 = r10.A07     // Catch:{ IOException -> 0x0126 }
            if (r0 > 0) goto L_0x00b3
            int r1 = r10.A06     // Catch:{ IOException -> 0x0126 }
            r0 = 1
            if (r1 <= 0) goto L_0x00b4
        L_0x00b3:
            r0 = 0
        L_0x00b4:
            r5.A0E(r0)     // Catch:{ IOException -> 0x0126 }
            java.lang.String r9 = "Cache data source open spec. Type:%s, Position:%d/%d, Length:%d, Vid:%s, Key:%s"
            r0 = 6
            java.lang.Object[] r8 = new java.lang.Object[r0]     // Catch:{ IOException -> 0x0126 }
            X.6xv r7 = r5.A0L     // Catch:{ IOException -> 0x0126 }
            r8[r11] = r7     // Catch:{ IOException -> 0x0126 }
            long r0 = r6.A03     // Catch:{ IOException -> 0x0126 }
            X.AnonymousClass000.A1Q(r8, r12, r0)     // Catch:{ IOException -> 0x0126 }
            long r0 = r6.A01     // Catch:{ IOException -> 0x0126 }
            X.AnonymousClass000.A1Q(r8, r13, r0)     // Catch:{ IOException -> 0x0126 }
            long r0 = r6.A02     // Catch:{ IOException -> 0x0126 }
            java.lang.Long r12 = java.lang.Long.valueOf(r0)     // Catch:{ IOException -> 0x0126 }
            r11 = 3
            r8[r11] = r12     // Catch:{ IOException -> 0x0126 }
            r11 = 4
            r8[r11] = r4     // Catch:{ IOException -> 0x0126 }
            r11 = 5
            r8[r11] = r2     // Catch:{ IOException -> 0x0126 }
            X.C161157p6.A02(r9, r8)     // Catch:{ IOException -> 0x0126 }
            boolean r2 = r5.A0A()     // Catch:{ IOException -> 0x0126 }
            if (r2 == 0) goto L_0x0103
            boolean r2 = r5.A0D()     // Catch:{ IOException -> 0x0126 }
            if (r2 != 0) goto L_0x0103
            boolean r2 = X.C161477pj.A04(r6)     // Catch:{ IOException -> 0x0126 }
            if (r2 != 0) goto L_0x00f1
            X.C161477pj.A03(r6)     // Catch:{ IOException -> 0x0126 }
        L_0x00f1:
            java.lang.String r8 = X.C161477pj.A01(r6)     // Catch:{ IOException -> 0x0126 }
            if (r8 == 0) goto L_0x0103
            java.util.Map r2 = r10.A0N     // Catch:{ IOException -> 0x0126 }
            r6.A00(r2)     // Catch:{ IOException -> 0x0126 }
            X.7nT r2 = X.C160337nT.A00()     // Catch:{ IOException -> 0x0126 }
            r2.A02(r4, r8)     // Catch:{ IOException -> 0x0126 }
        L_0x0103:
            r12 = 0
            r10 = -1
            int r2 = (r0 > r10 ? 1 : (r0 == r10 ? 0 : -1))
            if (r2 != 0) goto L_0x0112
            long r8 = r5.A03     // Catch:{ IOException -> 0x0126 }
            int r2 = (r8 > r12 ? 1 : (r8 == r12 ? 0 : -1))
            if (r2 <= 0) goto L_0x0112
            return r8
        L_0x0112:
            boolean r2 = r3.enableUpdateProgressiveContentLengthFromCache     // Catch:{ IOException -> 0x0126 }
            if (r2 == 0) goto L_0x0125
            int r2 = (r0 > r10 ? 1 : (r0 == r10 ? 0 : -1))
            if (r2 != 0) goto L_0x0125
            X.6xv r2 = X.C142866xv.A05     // Catch:{ IOException -> 0x0126 }
            if (r7 != r2) goto L_0x0125
            long r3 = r5.A02     // Catch:{ IOException -> 0x0126 }
            int r2 = (r3 > r12 ? 1 : (r3 == r12 ? 0 : -1))
            if (r2 <= 0) goto L_0x0125
            return r3
        L_0x0125:
            return r0
        L_0x0126:
            r2 = move-exception
            X.8LG r0 = r5.A0N
            X.8Kz r0 = r0.cache
            boolean r0 = r0.enableCacheInstrumentation
            if (r0 == 0) goto L_0x0134
            X.0UP r0 = r5.A0B
            r0.A02()
        L_0x0134:
            X.8xF r1 = r5.A09
            if (r1 == 0) goto L_0x013f
            boolean r0 = r5.A0C
            if (r0 == 0) goto L_0x0140
            r1.BeW()
        L_0x013f:
            throw r2
        L_0x0140:
            r1.BeY(r2)
            throw r2
        */
        throw new UnsupportedOperationException("Method not decompiled: X.C09890gv.Bfw(X.7pX):long");
    }

    public void cancel() {
        this.A0C = true;
        if (this.A0N.cancelOngoingRequest) {
            this.A07.cancel();
        }
    }

    public final C161387pX A00() {
        Uri uri;
        File file;
        AnonymousClass0Py r0 = this.A0A;
        long j = r0.A02;
        long j2 = r0.A01;
        if (j2 == -1) {
            j2 = Long.MAX_VALUE;
        }
        C172488Li r2 = this.A08;
        if (r2 != null && this.A0N.checkCachedLockedCacheSpan && r2.A08) {
            j -= r2.A05;
            j2 = Math.min(r2.A04 - j, j2);
        }
        if (this.A0N.enableVideoMemoryCache || r2 == null || (file = r2.A06) == null) {
            uri = null;
        } else {
            uri = Uri.fromFile(file);
        }
        AnonymousClass0Py r02 = this.A0A;
        long j3 = r02.A00;
        return new C161387pX(uri, r02.A05, r02.A06, (byte[]) null, r02.A03, j3, j, j2);
    }

    public final C172488Li A01() {
        AnonymousClass0Xd r1 = this.A0K;
        C172488Li A022 = A02(r1.A08());
        if (A022 == null) {
            return A02(r1.A08());
        }
        return A022;
    }

    public final C172488Li A02(C186458vL r8) {
        NavigableSet<C172488Li> B55 = r8.B55(this.A0A.A06);
        if (B55 == null) {
            return null;
        }
        for (C172488Li r5 : B55) {
            if (this.A0A.A02 < r5.A05) {
                return r5;
            }
        }
        return null;
    }

    public final C142646xX A03(C140846uc r12, C187478xH r13) {
        C172488Li Bpt;
        C142646xX r3 = C142646xX.A03;
        AnonymousClass0Py r0 = this.A0A;
        C140846uc r5 = r12;
        C187478xH r4 = r13;
        C172488Li Bpv = r13.Bpv(r12, r0.A06, r0.A02);
        this.A08 = Bpv;
        if (Bpv == null) {
            r3 = C142646xX.A04;
            if (!this.A0D) {
                boolean z = this.A0N.enableCacheBlockWithoutTimeout;
                AnonymousClass0Py r02 = this.A0A;
                if (z) {
                    Bpt = r13.Bpu(r12, r02.A06, r02.A02);
                } else {
                    Bpt = r4.Bpt(r5, r02.A06, r02.A02, (long) this.A0F);
                }
                this.A08 = Bpt;
            }
        } else if (Bpv.A08) {
            return C142646xX.A02;
        }
        return r3;
    }

    /* JADX WARNING: Code restructure failed: missing block: B:5:0x0014, code lost:
        if (r2.A08 == false) goto L_0x0016;
     */
    /* Code decompiled incorrectly, please refer to instructions dump. */
    public final void A05() {
        /*
            r14 = this;
            java.lang.String r0 = "exo-opencachedatasource"
            X.C153827c5.A01(r0)     // Catch:{ all -> 0x00cc }
            X.8Li r1 = r14.A08     // Catch:{ all -> 0x00cc }
            r0 = 0
            r14.A08(r0, r1)     // Catch:{ all -> 0x00cc }
            X.8Li r2 = r14.A08     // Catch:{ all -> 0x00cc }
            r12 = 1
            r13 = 0
            if (r2 == 0) goto L_0x0016
            boolean r1 = r2.A08     // Catch:{ all -> 0x00cc }
            r0 = 1
            if (r1 != 0) goto L_0x0017
        L_0x0016:
            r0 = 0
        L_0x0017:
            X.C159197lM.A02(r0)     // Catch:{ all -> 0x00cc }
            X.0Py r4 = r14.A0A     // Catch:{ all -> 0x00cc }
            long r5 = r4.A02     // Catch:{ all -> 0x00cc }
            long r0 = r2.A05     // Catch:{ all -> 0x00cc }
            long r5 = r5 - r0
            long r2 = r2.A04     // Catch:{ all -> 0x00cc }
            long r2 = r2 - r5
            long r0 = r4.A01     // Catch:{ all -> 0x00cc }
            r7 = -1
            int r4 = (r0 > r7 ? 1 : (r0 == r7 ? 0 : -1))
            if (r4 != 0) goto L_0x0031
            r0 = 9223372036854775807(0x7fffffffffffffff, double:NaN)
        L_0x0031:
            long r3 = java.lang.Math.min(r2, r0)     // Catch:{ all -> 0x00cc }
            X.7pX r8 = r14.A00()     // Catch:{ all -> 0x00cc }
            X.8LG r10 = r14.A0N     // Catch:{ all -> 0x00cc }
            boolean r0 = r10.enableVideoMemoryCache     // Catch:{ all -> 0x00cc }
            r11 = 3
            r9 = 2
            r1 = 6
            if (r0 != 0) goto L_0x008e
            X.8Li r0 = r14.A08     // Catch:{ all -> 0x00cc }
            boolean r0 = r0.A02     // Catch:{ all -> 0x00cc }
            if (r0 != 0) goto L_0x008e
            java.lang.String r7 = "Cache data source open spec(Cached). Type:%s, Offset:%d, FilePos:%d, Length:%d, Vid:%s, Key:%s"
            java.lang.Object[] r2 = new java.lang.Object[r1]     // Catch:{ all -> 0x00cc }
            X.6xv r0 = r14.A0L     // Catch:{ all -> 0x00cc }
            r2[r13] = r0     // Catch:{ all -> 0x00cc }
            X.0Py r13 = r14.A0A     // Catch:{ all -> 0x00cc }
            long r0 = r13.A00     // Catch:{ all -> 0x00cc }
            X.AnonymousClass000.A1Q(r2, r12, r0)     // Catch:{ all -> 0x00cc }
            X.AnonymousClass000.A1Q(r2, r9, r5)     // Catch:{ all -> 0x00cc }
            X.AnonymousClass000.A1Q(r2, r11, r3)     // Catch:{ all -> 0x00cc }
            X.7oI r0 = r14.A0M     // Catch:{ all -> 0x00cc }
            java.lang.String r1 = r0.A05()     // Catch:{ all -> 0x00cc }
            r0 = 4
            r2[r0] = r1     // Catch:{ all -> 0x00cc }
            java.lang.String r1 = r13.A06     // Catch:{ all -> 0x00cc }
            r0 = 5
            r2[r0] = r1     // Catch:{ all -> 0x00cc }
            X.C161157p6.A02(r7, r2)     // Catch:{ all -> 0x00cc }
            X.6KJ r5 = r14.A0J     // Catch:{ IOException -> 0x0087 }
            r5.Bfw(r8)     // Catch:{ IOException -> 0x0087 }
            X.8Kz r0 = r10.cache     // Catch:{ all -> 0x00cc }
            boolean r0 = r0.enableCacheInstrumentation     // Catch:{ all -> 0x00cc }
            if (r0 == 0) goto L_0x0082
            X.0UP r2 = r14.A0B     // Catch:{ all -> 0x00cc }
            X.0Py r0 = r14.A0A     // Catch:{ all -> 0x00cc }
            long r0 = r0.A00     // Catch:{ all -> 0x00cc }
            r2.A03(r0, r3)     // Catch:{ all -> 0x00cc }
        L_0x0082:
            r14.A02 = r3     // Catch:{ all -> 0x00cc }
            r14.A06 = r5     // Catch:{ all -> 0x00cc }
            goto L_0x00c8
        L_0x0087:
            r1 = move-exception
            X.6KJ r0 = r14.A0J     // Catch:{ all -> 0x00cc }
            r0.close()     // Catch:{ all -> 0x00cc }
            throw r1     // Catch:{ all -> 0x00cc }
        L_0x008e:
            java.lang.String r7 = "Cache data source open spec(MemoryCached). Type:%s, Offset:%d, CachePos:%d, Length:%d, Vid:%s, Key:%s"
            java.lang.Object[] r2 = new java.lang.Object[r1]     // Catch:{ all -> 0x00cc }
            X.6xv r0 = r14.A0L     // Catch:{ all -> 0x00cc }
            r2[r13] = r0     // Catch:{ all -> 0x00cc }
            X.0Py r10 = r14.A0A     // Catch:{ all -> 0x00cc }
            long r0 = r10.A00     // Catch:{ all -> 0x00cc }
            X.AnonymousClass000.A1Q(r2, r12, r0)     // Catch:{ all -> 0x00cc }
            X.AnonymousClass000.A1Q(r2, r9, r5)     // Catch:{ all -> 0x00cc }
            X.AnonymousClass000.A1Q(r2, r11, r3)     // Catch:{ all -> 0x00cc }
            X.7oI r0 = r14.A0M     // Catch:{ all -> 0x00cc }
            java.lang.String r1 = r0.A05()     // Catch:{ all -> 0x00cc }
            r0 = 4
            r2[r0] = r1     // Catch:{ all -> 0x00cc }
            java.lang.String r1 = r10.A06     // Catch:{ all -> 0x00cc }
            r0 = 5
            r2[r0] = r1     // Catch:{ all -> 0x00cc }
            X.C161157p6.A02(r7, r2)     // Catch:{ all -> 0x00cc }
            X.0gp r2 = new X.0gp     // Catch:{ all -> 0x00cc }
            r2.<init>()     // Catch:{ all -> 0x00cc }
            X.0Xd r0 = r14.A0K     // Catch:{ all -> 0x00cc }
            X.8xH r1 = r0.A08()     // Catch:{ all -> 0x00cc }
            X.8Li r0 = r14.A08     // Catch:{ all -> 0x00cc }
            r2.A00(r8, r0, r1)     // Catch:{ all -> 0x00cc }
            r14.A02 = r3     // Catch:{ all -> 0x00cc }
            r14.A06 = r2     // Catch:{ all -> 0x00cc }
        L_0x00c8:
            X.C153827c5.A00()
            return
        L_0x00cc:
            r0 = move-exception
            X.C153827c5.A00()
            throw r0
        */
        throw new UnsupportedOperationException("Method not decompiled: X.C09890gv.A05():void");
    }

    /* JADX WARNING: Code restructure failed: missing block: B:3:0x0014, code lost:
        if (r2 != -1) goto L_0x0016;
     */
    /* Code decompiled incorrectly, please refer to instructions dump. */
    public final void A06() {
        /*
            r14 = this;
            X.0Xd r0 = r14.A0K
            X.8xH r1 = r0.A08()
            if (r1 == 0) goto L_0x0019
            X.0Py r0 = r14.A0A
            java.lang.String r0 = r0.A06
            long r2 = r1.BDo(r0)
            r4 = -1
            int r0 = (r2 > r4 ? 1 : (r2 == r4 ? 0 : -1))
            if (r0 == 0) goto L_0x0019
        L_0x0016:
            r14.A03 = r2
            return
        L_0x0019:
            X.0Py r0 = r14.A0A
            android.net.Uri r3 = r0.A04
            r6 = 0
            long r8 = r0.A00
            r10 = 0
            r12 = 1
            java.lang.String r5 = r0.A06
            int r7 = r0.A03
            X.7ni r4 = r0.A05
            X.7pX r2 = new X.7pX
            r2.<init>(r3, r4, r5, r6, r7, r8, r10, r12)
            X.8xE r0 = r14.A07     // Catch:{ IOException -> 0x004a }
            r0.Bfw(r2)     // Catch:{ IOException -> 0x004a }
            java.util.Map r2 = r0.BCF()
            X.8LG r0 = r14.A0N
            boolean r0 = r0.enableCaseInsensitiveHttpResponseHeaderKey
            long r2 = X.C161477pj.A00(r2, r0)
            if (r1 == 0) goto L_0x0016
            X.0Py r0 = r14.A0A
            java.lang.String r0 = r0.A06
            r1.Bnd(r0, r2)
            goto L_0x0016
        L_0x004a:
            r1 = move-exception
            X.8xE r0 = r14.A07
            r0.close()
            throw r1
        */
        throw new UnsupportedOperationException("Method not decompiled: X.C09890gv.A06():void");
    }

    public final void A07() {
        if (this.A0N.alwaysPerformContentLengthUpdateFirst) {
            A06();
        }
    }

    public final void A08(C186458vL r2, C172488Li r3) {
        if (r3 == null) {
            if (r2 != null) {
                r2.hashCode();
            }
            hashCode();
            return;
        }
        if (r2 != null) {
            r2.hashCode();
        }
        hashCode();
        File file = r3.A06;
        if (file != null) {
            file.getPath();
        }
    }

    public final void A09(C172488Li r4) {
        AnonymousClass0Xd r2 = this.A0K;
        if (r2.A08() != null) {
            if (this.A0N.cache.enableCacheInstrumentation) {
                C09870gt.A00().A02(this.A08);
            }
            r2.A08().Bip(r4);
        }
    }

    public final boolean A0A() {
        FbAutogeneratedSettings fbAutogeneratedSettings = this.A0N.autogenSettings;
        if (fbAutogeneratedSettings == null || !fbAutogeneratedSettings.enableSloHttpHeaderLogging) {
            return false;
        }
        return true;
    }

    public final boolean A0B() {
        C187478xH A082;
        AnonymousClass8LG r5;
        String str;
        long j;
        boolean z;
        try {
            C153827c5.A01("exo-openhttpdatastream");
            C172488Li A012 = A01();
            long j2 = this.A0A.A01;
            if (j2 == -1) {
                j2 = -1;
            } else if (j2 == -1) {
                j2 = Long.MAX_VALUE;
            }
            AnonymousClass0Xd r34 = this.A0K;
            A082 = r34.A08();
            r5 = this.A0N;
            if (!r5.useShortKey || !r5.enableLongCacheKeyForContentLength) {
                str = this.A0A.A06;
            } else {
                AnonymousClass0Py r1 = this.A0A;
                String str2 = r1.A06;
                C160777oI r0 = this.A0M;
                String A052 = r0.A05();
                Uri uri = r1.A04;
                str = C161157p6.A00(uri, str2, A052, this.A0Q, false, r0.A07(), false, r5.skipThumbnailCacheKey);
            }
            if (A082 != null) {
                long BDo = A082.BDo(str);
                if (BDo != -1) {
                    long j3 = this.A0A.A02;
                    if (j3 >= BDo) {
                        Object[] objArr = new Object[2];
                        AnonymousClass000.A1Q(objArr, 0, BDo);
                        AnonymousClass000.A1Q(objArr, 1, j3);
                        Log.w("FbHttpCacheDataSource", String.format("Skip Http request because content length is %s and position is %s", objArr));
                        C153827c5.A00();
                        return false;
                    }
                }
            }
            if (A012 != null) {
                j2 = Math.min(A012.A05 - this.A0A.A02, j2);
            }
            AnonymousClass0Py r10 = this.A0A;
            Uri uri2 = r10.A04;
            long j4 = r10.A00;
            long j5 = r10.A02;
            C161387pX r22 = new C161387pX(uri2, r10.A05, r10.A06, (byte[]) null, r10.A03, j4, j5, j2);
            C160487ni r15 = r22.A05;
            C160087n1 r12 = r15.A0F;
            C160777oI r13 = this.A0M;
            r12.A00 = r13.A01();
            r12.A01 = r13.A02();
            C187448xE r122 = this.A07;
            long Bfw = r122.Bfw(r22);
            Map BCF = r122.BCF();
            String A053 = r13.A05();
            long A002 = C161477pj.A00(BCF, r5.enableCaseInsensitiveHttpResponseHeaderKey);
            this.A03 = A002;
            if (r5.enableVodContentLengthLogging) {
                this.A09.Bm1(A002);
            }
            if (A082 != null) {
                A082.Bnd(str, this.A03);
            }
            AnonymousClass0Py r9 = this.A0A;
            if (r9.A01 == -1) {
                r9.A02(this.A03);
            }
            Object[] objArr2 = new Object[7];
            C142866xv r02 = this.A0L;
            C142866xv r16 = r02;
            objArr2[0] = r02;
            AnonymousClass000.A1Q(objArr2, 1, r22.A01);
            Long valueOf = Long.valueOf(j2);
            objArr2[2] = valueOf;
            Long valueOf2 = Long.valueOf(Bfw);
            objArr2[3] = valueOf2;
            objArr2[4] = A053;
            objArr2[5] = r9.A06;
            objArr2[6] = Integer.valueOf(r15.A07);
            C161157p6.A02("Cache data source open spec(HTTP). Type:%s, Offset:%d, Length:%d, OpenLength:%d, Vid:%s, Key:%s, seq:%d", objArr2);
            this.A06 = r122;
            if (r5.cache.enableCacheInstrumentation) {
                this.A0B.A04(this.A0A.A00, Bfw);
            }
            C172488Li r92 = this.A08;
            if (r92 != null && !r92.A08) {
                if (Bfw > 0) {
                    boolean z2 = this.A0S;
                    if (z2) {
                        j = this.A0H;
                    } else if (Bfw <= ((long) r34.A00)) {
                        j = Long.MAX_VALUE;
                    }
                    boolean z3 = this.A0P;
                    if (!z3 || (this.A0R && !z2)) {
                        z = false;
                    } else {
                        z = true;
                    }
                    boolean z4 = this.A0T;
                    if (A0C()) {
                        C09810gn r123 = new C09810gn(r34.A08(), j, z4);
                        C187478xH A083 = r34.A08();
                        boolean z5 = this.A0U;
                        int i = this.A0G;
                        this.A05 = new C09800gm(r123, new C1675081i(A083, this.A08, i, j, this.A0I, z5, z));
                    } else if (r5.enableVideoMemoryCache) {
                        this.A05 = new C09810gn(r34.A08(), j, z4);
                    } else {
                        C187478xH A084 = r34.A08();
                        boolean z6 = this.A0U;
                        int i2 = this.A0G;
                        this.A05 = new C1675081i(A084, this.A08, i2, j, this.A0I, z6, z3);
                    }
                    AnonymousClass0Py r52 = this.A0A;
                    Uri uri3 = r52.A04;
                    long j6 = r52.A00;
                    long j7 = r52.A02;
                    C161387pX r20 = new C161387pX(uri3, r52.A05, r52.A06, (byte[]) null, r52.A03, j6, j7, Bfw);
                    this.A05.Bfy(r20);
                    Object[] objArr3 = new Object[6];
                    objArr3[0] = r16;
                    AnonymousClass000.A1Q(objArr3, 1, r20.A01);
                    AnonymousClass001.A1H(valueOf, valueOf2, objArr3);
                    objArr3[4] = A053;
                    objArr3[5] = this.A0A.A06;
                    C161157p6.A02("Cache data sink open spec. Type:%s, Offset:%d, Length:%d, OpenLength:%d Vid:%s, Key:%s", objArr3);
                }
                A09(r92);
                this.A08 = null;
            }
            C153827c5.A00();
            return true;
        } catch (IOException e) {
            C187448xE r2 = this.A07;
            r2.close();
            if (e instanceof AnonymousClass6KQ) {
                AnonymousClass6KQ r3 = (AnonymousClass6KQ) e;
                if (r3.responseCode == 416) {
                    long A003 = C161477pj.A00(r2.BCF(), r5.enableCaseInsensitiveHttpResponseHeaderKey);
                    this.A03 = A003;
                    if (A082 != null) {
                        A082.Bnd(str, A003);
                    }
                    AnonymousClass0Py r8 = this.A0A;
                    if (r8.A01 == -1) {
                        long j8 = this.A03;
                        if (j8 > 0) {
                            r8.A02(j8);
                        }
                    }
                    Log.e("FbHttpCacheDataSource", String.format("Returning length 0 after 416 response", new Object[0]));
                    if (r5.enable416Logging) {
                        this.A09.BeY(r3);
                    }
                }
            }
            throw e;
        } catch (C140446tk e2) {
            throw AnonymousClass002.A0C(e2.getMessage());
        } catch (Throwable th) {
            C153827c5.A00();
            throw th;
        }
    }

    public final boolean A0C() {
        AnonymousClass8LG r1 = this.A0N;
        if (!r1.enableVideoHybridCache || !this.A0S || !r1.enableHybridCacheForPrefetch) {
            return false;
        }
        return true;
    }

    public final boolean A0D() {
        String A052 = this.A0M.A05();
        if (A052 == null || !C160337nT.A00().A01(A052).booleanValue()) {
            return false;
        }
        return true;
    }

    public final boolean A0E(boolean z) {
        boolean z2;
        C140846uc r2;
        C187458xF r11;
        long j;
        C187458xF r8;
        String str;
        String str2;
        try {
            C153827c5.A01("exo-opennextdatasource");
            boolean A1W = AnonymousClass000.A1W(this.A06);
            A04();
            AnonymousClass0Py r82 = this.A0A;
            long j2 = r82.A01;
            if (j2 == -1) {
                j2 = Long.MAX_VALUE;
            }
            if (j2 != 0) {
                AnonymousClass8LG r4 = this.A0N;
                if (r4.shouldLoadBinaryDataFromManifest) {
                    C160487ni r1 = r82.A05;
                    if (!(!r1.A00() || (str = r1.A0H) == null || (str2 = r1.A0G) == null)) {
                        C09820go r12 = new C09820go(str, str2);
                        this.A06 = r12;
                        r12.Bfw(this.A0A.A00());
                        C153827c5.A00();
                        return true;
                    }
                }
                C187478xH A082 = this.A0K.A08();
                C142646xX r83 = C142646xX.A03;
                if (A082 != null) {
                    if (r4.enableVrlQplLoggingEvents && (r8 = this.A09) != null && !this.A0S) {
                        AnonymousClass0Py r13 = this.A0A;
                        long j3 = r13.A00;
                        if (j3 == 0) {
                            r8.BUb();
                        } else if (r13.A05.A07 == 0) {
                            r8.BTa(j3, r13.A01);
                        }
                    }
                    try {
                        boolean z3 = this.A0S;
                        if (z3) {
                            r2 = C140846uc.PREFETCH;
                        } else {
                            r2 = C140846uc.PLAYBACK;
                        }
                        if (z) {
                            r2 = C140846uc.INIT_SEGMENT;
                        }
                        if (r4.enableLogSemiCachedEvents) {
                            r83 = A03(r2, A082);
                        } else {
                            r83 = C142646xX.A02;
                            if (this.A0D) {
                                AnonymousClass0Py r0 = this.A0A;
                                this.A08 = A082.Bpv(r2, r0.A06, r0.A02);
                            } else if (r4.enableCacheBlockWithoutTimeout) {
                                AnonymousClass0Py r02 = this.A0A;
                                this.A08 = A082.Bpu(r2, r02.A06, r02.A02);
                            } else {
                                AnonymousClass0Py r03 = this.A0A;
                                String str3 = r03.A06;
                                this.A08 = A082.Bpt(r2, str3, r03.A02, (long) this.A0F);
                            }
                        }
                        C172488Li r14 = this.A08;
                        if (r14 != null || !z3) {
                            if (r4.enableVrlQplLoggingEvents && (r11 = this.A09) != null && !z3) {
                                AnonymousClass0Py r9 = this.A0A;
                                long j4 = r9.A00;
                                if (j4 == 0) {
                                    r11.BUa(r83);
                                } else if (r9.A05.A07 == 0) {
                                    long j5 = r9.A01;
                                    if (!r4.fixNullCacheSpan) {
                                        j = r14.A04;
                                    } else if (r14 != null) {
                                        j = r14.A04;
                                    } else {
                                        j = -1;
                                    }
                                    r11.BTZ(r83, j4, j5, j);
                                }
                            }
                            A08(A082, this.A08);
                        } else {
                            throw AnonymousClass002.A0C("Timeout when obtain cache span lock");
                        }
                    } catch (InterruptedException unused) {
                        C153827c5.A00();
                        return false;
                    }
                }
                this.A0E = false;
                C172488Li r15 = this.A08;
                if (r15 == null || !r15.A08) {
                    z2 = true;
                } else {
                    C159197lM.A02(AnonymousClass000.A1T(r15.A02() ? 1 : 0));
                    C187458xF r16 = this.A09;
                    if (r16 != null) {
                        r16.Bea(this.A0A.A00(), r83);
                    }
                    A05();
                    z2 = false;
                }
                if (r4.cache.enableCacheInstrumentation) {
                    C09870gt.A00().A03(this.A08, this.A0M, this.A0A.A04.toString());
                }
                if (!z2) {
                    A07();
                    C153827c5.A00();
                    return true;
                } else if (this.A0D) {
                    C161157p6.A01("FbHttpCacheDataSource", "shouldOpenHttp source, but read from cache only is true: %s", this.A0M.A05());
                } else if (!A1W || !this.A0S) {
                    if (this.A08 == null) {
                        C161157p6.A01("FbHttpCacheDataSource", "Cache span locked. Skipping caching %s", this.A0M.A05());
                    }
                    boolean A0B2 = A0B();
                    C153827c5.A00();
                    return A0B2;
                } else {
                    A07();
                }
            }
        } catch (IOException | IllegalArgumentException e) {
            Log.e("FbHttpCacheDataSource", String.format("Caught exception reading from manifest data source so ignoring", new Object[0]), e);
        } catch (Throwable th) {
            C153827c5.A00();
            throw th;
        }
        C153827c5.A00();
        return false;
    }

    public Uri BE6() {
        return null;
    }

    public void close() {
        if (this.A0N.cache.enableCacheInstrumentation) {
            C09870gt.A00().A04(this.A0B);
        }
        A04();
        this.A0A = null;
    }

    /* JADX WARNING: Can't wrap try/catch for region: R(11:17|(1:25)|26|(2:28|(3:30|31|32))|43|44|(2:52|53)|54|55|(3:57|(1:59)|60)|61) */
    /* JADX WARNING: Code restructure failed: missing block: B:42:0x0097, code lost:
        if (r4 != -1) goto L_0x0099;
     */
    /* JADX WARNING: Missing exception handler attribute for start block: B:54:0x00b7 */
    /* JADX WARNING: Removed duplicated region for block: B:57:0x00bb A[Catch:{ IOException -> 0x00c4 }] */
    /* Code decompiled incorrectly, please refer to instructions dump. */
    public int read(byte[] r19, int r20, int r21) {
        /*
            r18 = this;
            r7 = r18
            X.7pX r8 = r7.A00()     // Catch:{ IOException -> 0x00c4 }
            boolean r0 = r7.A0E     // Catch:{ IOException -> 0x00c4 }
            r6 = 0
            r9 = 1
            if (r0 != 0) goto L_0x001f
            X.8xF r5 = r7.A09     // Catch:{ IOException -> 0x00c4 }
            if (r5 == 0) goto L_0x001d
            long r3 = r7.A03     // Catch:{ IOException -> 0x00c4 }
            r1 = -1
            int r0 = (r3 > r1 ? 1 : (r3 == r1 ? 0 : -1))
            boolean r0 = X.AnonymousClass000.A1T(r0)
            r5.Beb(r8, r7, r9, r0)     // Catch:{ IOException -> 0x00c4 }
        L_0x001d:
            r7.A0E = r9     // Catch:{ IOException -> 0x00c4 }
        L_0x001f:
            X.8uF r0 = r7.A06     // Catch:{ IOException -> 0x00c4 }
            r5 = -1
            if (r0 != 0) goto L_0x0034
            java.lang.String r2 = "Trying to read when datasource isn't set. cache-only: %b"
            java.lang.Object[] r1 = new java.lang.Object[r9]     // Catch:{ IOException -> 0x00c4 }
            boolean r0 = r7.A0D     // Catch:{ IOException -> 0x00c4 }
            java.lang.Boolean r0 = java.lang.Boolean.valueOf(r0)     // Catch:{ IOException -> 0x00c4 }
            r1[r6] = r0     // Catch:{ IOException -> 0x00c4 }
            X.C161157p6.A02(r2, r1)     // Catch:{ IOException -> 0x00c4 }
            return r5
        L_0x0034:
            r14 = 0
            r10 = r19
            r9 = r20
            r12 = r21
            int r4 = r0.read(r10, r9, r12)     // Catch:{ IOException -> 0x00c4 }
            if (r4 <= 0) goto L_0x0085
            long r2 = r7.A04     // Catch:{ IOException -> 0x00c4 }
            long r0 = (long) r4     // Catch:{ IOException -> 0x00c4 }
            long r2 = r2 + r0
            r7.A04 = r2     // Catch:{ IOException -> 0x00c4 }
            X.8LG r11 = r7.A0N     // Catch:{ IOException -> 0x00c4 }
            X.8Kz r0 = r11.cache     // Catch:{ IOException -> 0x00c4 }
            long r0 = r0.skipDeadSpanLockThresholdMs     // Catch:{ IOException -> 0x00c4 }
            int r13 = (r0 > r14 ? 1 : (r0 == r14 ? 0 : -1))
            if (r13 <= 0) goto L_0x006e
            X.8uF r1 = r7.A06     // Catch:{ IOException -> 0x00c4 }
            X.8xE r0 = r7.A07     // Catch:{ IOException -> 0x00c4 }
            if (r1 != r0) goto L_0x006e
            X.8Li r13 = r7.A08     // Catch:{ IOException -> 0x00c4 }
            if (r13 == 0) goto L_0x006e
            long r0 = r7.A01     // Catch:{ IOException -> 0x00c4 }
            long r16 = r2 - r0
            r14 = 5120(0x1400, double:2.5296E-320)
            int r0 = (r16 > r14 ? 1 : (r16 == r14 ? 0 : -1))
            if (r0 <= 0) goto L_0x006e
            r7.A01 = r2     // Catch:{ IOException -> 0x00c4 }
            long r0 = android.os.SystemClock.elapsedRealtime()     // Catch:{ IOException -> 0x00c4 }
            r13.A09 = r0     // Catch:{ IOException -> 0x00c4 }
        L_0x006e:
            int r11 = r11.numOfBytesBeforeLoaderThreadSleep     // Catch:{ IOException -> 0x00c4 }
            if (r11 <= 0) goto L_0x0099
            long r2 = r7.A04     // Catch:{ IOException -> 0x00c4 }
            long r0 = r7.A00     // Catch:{ IOException -> 0x00c4 }
            long r13 = r2 - r0
            long r0 = (long) r11     // Catch:{ IOException -> 0x00c4 }
            int r11 = (r13 > r0 ? 1 : (r13 == r0 ? 0 : -1))
            if (r11 < 0) goto L_0x0099
            r7.A00 = r2     // Catch:{ IOException -> 0x00c4 }
            r0 = 1
            java.lang.Thread.sleep(r0)     // Catch:{ InterruptedException -> 0x0085 }
            goto L_0x0099
        L_0x0085:
            if (r4 != r5) goto L_0x0096
            boolean r0 = r7.A0E(r6)     // Catch:{ IOException -> 0x00c4 }
            if (r0 == 0) goto L_0x00c3
            X.8uF r0 = r7.A06     // Catch:{ IOException -> 0x00c4 }
            int r4 = r0.read(r10, r9, r12)     // Catch:{ IOException -> 0x00c4 }
            if (r4 != r5) goto L_0x0096
            return r4
        L_0x0096:
            r0 = 0
            if (r4 == r5) goto L_0x009a
        L_0x0099:
            r0 = 1
        L_0x009a:
            X.C159197lM.A02(r0)     // Catch:{ IOException -> 0x00c4 }
            X.0Py r0 = r7.A0A     // Catch:{ IOException -> 0x00c4 }
            r0.A01(r4)     // Catch:{ IOException -> 0x00c4 }
            X.8uF r0 = r7.A06     // Catch:{ IOException -> 0x00c4 }
            X.8xE r2 = r7.A07     // Catch:{ IOException -> 0x00c4 }
            if (r0 != r2) goto L_0x00b7
            X.8sS r1 = r7.A05     // Catch:{ IOException -> 0x00c4 }
            if (r1 == 0) goto L_0x00b7
            X.8Li r0 = r7.A08     // Catch:{ IOException -> 0x00c4 }
            if (r0 == 0) goto L_0x00b7
            boolean r0 = r0.A08     // Catch:{ IOException -> 0x00c4 }
            if (r0 != 0) goto L_0x00b7
            r1.write(r10, r9, r4)     // Catch:{ IOException -> 0x00b7 }
        L_0x00b7:
            X.8xF r1 = r7.A09     // Catch:{ IOException -> 0x00c4 }
            if (r1 == 0) goto L_0x00c3
            X.8uF r0 = r7.A06     // Catch:{ IOException -> 0x00c4 }
            if (r0 != r2) goto L_0x00c0
            r6 = 1
        L_0x00c0:
            r1.BO0(r8, r7, r4, r6)     // Catch:{ IOException -> 0x00c4 }
        L_0x00c3:
            return r4
        L_0x00c4:
            r1 = move-exception
            X.8LG r0 = r7.A0N
            X.8Kz r0 = r0.cache
            boolean r0 = r0.enableCacheInstrumentation
            if (r0 == 0) goto L_0x00d2
            X.0UP r0 = r7.A0B
            r0.A02()
        L_0x00d2:
            X.8xF r0 = r7.A09
            if (r0 == 0) goto L_0x00d9
            r0.BeY(r1)
        L_0x00d9:
            throw r1
        */
        throw new UnsupportedOperationException("Method not decompiled: X.C09890gv.read(byte[], int, int):int");
    }

    public void Awq(C184768sU r2) {
        r2.getClass();
        if (r2 instanceof C187458xF) {
            this.A09 = (C187458xF) r2;
        } else {
            this.A09 = new C1676982d(r2);
        }
    }

    public C09890gv(C187448xE r4, C187458xF r5, AnonymousClass0Xd r6, C142866xv r7, C160777oI r8, AnonymousClass8LG r9, AtomicBoolean atomicBoolean, int i, long j, long j2, boolean z, boolean z2, boolean z3, boolean z4, boolean z5, boolean z6) {
        this.A0K = r6;
        this.A0M = r8;
        this.A07 = r4;
        this.A0J = new AnonymousClass6KJ();
        this.A05 = null;
        this.A0S = z;
        this.A09 = r5;
        this.A03 = 0;
        this.A02 = 0;
        this.A0F = i;
        this.A0H = j;
        this.A0T = z2;
        this.A0Q = z3;
        this.A0C = false;
        this.A0D = z4;
        this.A0N = r9;
        this.A0O = atomicBoolean;
        this.A0L = r7;
        this.A0U = r9.useBufferedCacheDataSink;
        this.A0G = r9.bufferedCacheDataSinkSize;
        this.A0P = z5;
        this.A0R = z6;
        this.A0I = j2;
    }
}
