package X;

import com.whatsapp.R;

/* renamed from: X.79t  reason: invalid class name and case insensitive filesystem */
public final class C1463179t {
    public static final int[] A00 = {16842964, 16843919, 16844096, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved};
    public static final int[] A01 = {R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved};
    public static final int[] A02 = {R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved};
    public static final int[] A03 = {16843072, R.attr.f3nameremoved, R.attr.f3nameremoved};
    public static final int[] A04 = {16843039, 16843040, 16843840, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved};
    public static final int[] A05 = {16842804, 16842901, 16842904, 16842923, 16843039, 16843087, 16843237, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved};
    public static final int[] A06 = {R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved};
    public static final int[] A07 = {R.attr.f3nameremoved, R.attr.f3nameremoved};
    public static final int[] A08 = {R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved};
    public static final int[] A09 = {R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved};
    public static final int[] A0A = {R.attr.f3nameremoved, R.attr.f3nameremoved};
    public static final int[] A0B = {R.attr.f3nameremoved, R.attr.f3nameremoved};
    public static final int[] A0C = {16842766, 16843379, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved};
    public static final int[] A0D = {R.attr.f3nameremoved};
    public static final int[] A0E = {R.attr.f3nameremoved, R.attr.f3nameremoved};
    public static final int[] A0F = {16843017, 16843264, R.attr.f3nameremoved};
    public static final int[] A0G = {R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved};
    public static final int[] A0H = {16843296, 16843916, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved};
    public static final int[] A0I = {16842964, 16843191, 16843192, 16843193, 16843194, 16843237, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved};
    public static final int[] A0J = {16842766, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved};
    public static final int[] A0K = {16843277, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved};
    public static final int[] A0L = {16843191, 16843192, 16843193, 16843194, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved};
    public static final int[] A0M = {16843015, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved};
    public static final int[] A0N = {R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved};
    public static final int[] A0O = {R.attr.f3nameremoved, R.attr.f3nameremoved};
    public static final int[] A0P = {R.attr.f3nameremoved, R.attr.f3nameremoved};
    public static final int[] A0Q = {16843958, 16844159, R.attr.f3nameremoved};
    public static final int[] A0R = {16842804, 16844159, R.attr.f3nameremoved};
    public static final int[] A0S = {R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved};
    public static final int[] A0T = {16843093, 16843097, 16843173, R.attr.f3nameremoved, R.attr.f3nameremoved};
    public static final int[] A0U = {R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved};
    public static final int[] A0V = {R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved};
    public static final int[] A0W = {R.attr.f3nameremoved};
    public static final int[] A0X = {R.attr.f3nameremoved};
    public static final int[] A0Y = {R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved};
    public static final int[] A0Z = {R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved};
    public static final int[] A0a = {16843039, 16843040, 16843840, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved};
    public static final int[] A0b = {16843039, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved};
    public static final int[] A0c = {R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved};
    public static final int[] A0d = {16842901, 16842902, 16842903, 16842904, 16842906, 16842907, 16843105, 16843106, 16843107, 16843108, 16843692, 16844165, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved};
    public static final int[] A0e = {R.attr.f3nameremoved};
    public static final int[] A0f = {16842766, 16842906, 16843039, 16843071, 16843088, 16843095, 16843098, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved, R.attr.f3nameremoved};
    public static final int[] A0g = {16842804, R.attr.f3nameremoved, R.attr.f3nameremoved};
}
