package X;

import java.io.InputStream;
import java.io.OutputStream;
import java.util.List;
import java.util.Map;

/* renamed from: X.8Hn  reason: invalid class name and case insensitive filesystem */
public class C171558Hn implements C179548jK {
    public byte A00;
    public int A01 = 0;
    public int A02;
    public int A03 = 0;
    public long A04 = 0;
    public long A05 = 0;
    public long A06 = 0;
    public C182788oz A07;
    public C140726uO A08;
    public C151467Ux A09;
    public C152927aO A0A;
    public C151487Uz A0B;
    public AnonymousClass8P3 A0C;
    public C152877aJ A0D;
    public C388629o A0E;
    public AnonymousClass2BZ A0F;
    public AnonymousClass7TD A0G;
    public C388729p A0H;
    public C388829q A0I;
    public AnonymousClass7IZ A0J;
    public C147537Er A0K;
    public AnonymousClass8P4 A0L;
    public InputStream A0M;
    public OutputStream A0N;
    public String A0O;
    public String A0P;
    public String A0Q;
    public List A0R;
    public List A0S;
    public List A0T;
    public Map A0U;
    public short A0V = 0;
    public short A0W = 0;
    public boolean A0X = false;
    public boolean A0Y = false;
    public boolean A0Z = false;
    public boolean A0a;
    public boolean A0b;
    public boolean A0c = false;
    public boolean A0d;
    public boolean A0e;
    public boolean A0f = false;
    public boolean A0g;
    public byte[] A0h;
    public byte[] A0i;
    public byte[] A0j;
    public byte[] A0k;
    public byte[] A0l;
    public byte[] A0m;
    public byte[] A0n;
}
