package X;

/* renamed from: X.9Jn  reason: invalid class name and case insensitive filesystem */
public enum C192389Jn {
    UNKNOWN,
    PAYLOAD_FORMAT_INDICATOR,
    POINT_OF_INFORMATION_METHOD,
    MERCHANT_ACCOUNT_INFORMATION_VISA,
    MERCHANT_ACCOUNT_INFORMATION_MASTERCARD,
    MERCHANT_ACCOUNT_INFORMATION_DISCOVER,
    MERCHANT_ACCOUNT_INFORMATION_AMEX,
    MERCHANT_ACCOUNT_INFORMATION_JCB,
    MERCHANT_ACCOUNT_INFORMATION_UNION_PAY,
    MERCHANT_ACCOUNT_INFORMATION_RESERVED_BY_EMV_CO,
    MERCHANT_ACCOUNT_INFORMATION_TEMPLATE,
    MERCHANT_CATEGORY_CODE,
    TRANSACTION_CURRENCY,
    TRANSACTION_AMOUNT,
    COUNTRY_CODE,
    MERCHANT_NAME,
    MERCHANT_CITY,
    POSTAL_CODE,
    ADDITIONAL_DATA_FIELD_TEMPLATE,
    CRC16,
    UNRESERVED_TEMPLATES;

    /* access modifiers changed from: public */
    static {
        C192389Jn[] r3;
        A00 = new C73653fr(r3);
    }
}
