package X;

import android.text.TextUtils;

/* renamed from: X.2uo  reason: invalid class name and case insensitive filesystem */
public class C58162uo {
    public static final String A00;
    public static final String A01;
    public static final String A02;
    public static final String A03;
    public static final String A04;
    public static final String A05;
    public static final String A06;
    public static final String A07;
    public static final String A08;
    public static final String A09;
    public static final String A0A;
    public static final String A0B;
    public static final String A0C;
    public static final String A0D;
    public static final String A0E;
    public static final String A0F;
    public static final String A0G;
    public static final String A0H;
    public static final String A0I;
    public static final String A0J;
    public static final String A0K;
    public static final String A0L;
    public static final String A0M;
    public static final String A0N;
    public static final String[] A0O;

    static {
        C57212tH.A01("message", AnonymousClass2C5.A03);
        StringBuilder A0l = AnonymousClass000.A0l("SELECT ");
        String str = AnonymousClass2C5.A01;
        A0l.append(str);
        A0l.append(" FROM ");
        A0l.append("available_message_view");
        A0l.append(" WHERE ");
        A0l.append("chat_row_id = ?");
        A0l.append(" AND ");
        A0l.append("from_me = 0");
        A0l.append(" AND ");
        A0l.append("sort_id <= ?");
        A0l.append(" AND ");
        A0l.append("sort_id > ?");
        A0l.append(" AND ");
        A0l.append("status NOT IN (16, 10)");
        A0l.append(" AND ");
        A0l.append("message_type NOT IN ('8', '10', '15')");
        A0l.append(" ORDER BY sort_id DESC ");
        A0N = AnonymousClass000.A0X("LIMIT 4096", A0l);
        String[] strArr = {"key_from_me", "key_id", "status", "needs_push", "data", "timestamp", "media_url", "media_mime_type", "media_wa_type", "media_size", "media_name", "media_caption", "media_hash", "media_duration", "origin", "latitude", "longitude", "thumb_image", "remote_resource", "raw_data", "recipient_count", "participant_hash", "starred", "quoted_row_id", "mentioned_jids", "multicast_id", "edit_version", "receipt_server_timestamp", "media_enc_hash", "payment_transaction_id", "forwarded", "preview_type", "received_timestamp", "lookup_tables", "future_message_type", "message_add_on_flags", "view_mode", "_id"};
        A0O = strArr;
        A00 = TextUtils.join(", ", strArr);
        StringBuilder A0o = AnonymousClass001.A0o();
        C18260x0.A0p("   SELECT ", str, " FROM ", "available_message_view", A0o);
        String A0V = AnonymousClass000.A0V(" WHERE ", "chat_row_id = ?", A0o);
        A0K = A0V;
        StringBuilder A0m = AnonymousClass000.A0m(A0V, " AND ");
        A0m.append("message_type = ?");
        A09 = AnonymousClass000.A0X(" ORDER BY sort_id DESC", A0m);
        StringBuilder A0o2 = AnonymousClass001.A0o();
        C18260x0.A0p(A0V, " AND ", "message_type", " NOT IN ('", A0o2);
        A00(A0o2);
        A0o2.append(15);
        A0o2.append("', '");
        A0o2.append(19);
        C18260x0.A0p("') AND ", "from_me = 0", " ORDER BY sort_id DESC", " LIMIT ?", A0o2);
        A05 = A0o2.toString();
        StringBuilder A0o3 = AnonymousClass001.A0o();
        C18260x0.A0p(A0V, " AND ", "message_type", " NOT IN ('", A0o3);
        A00(A0o3);
        A0o3.append(19);
        C18260x0.A0p("') AND ", "from_me = 0", " ORDER BY sort_id DESC", " LIMIT ?", A0o3);
        A06 = A0o3.toString();
        StringBuilder A0o4 = AnonymousClass001.A0o();
        C18260x0.A0p(A0V, " AND ", "message_type", " NOT IN ('", A0o4);
        A00(A0o4);
        A0o4.append(19);
        A0o4.append("') AND ");
        A0o4.append("from_me = 0");
        A07 = AnonymousClass000.A0U(" AND (view_mode IS NULL OR view_mode = 0) ", " ORDER BY sort_id DESC", " LIMIT ?", A0o4);
        StringBuilder A0o5 = AnonymousClass001.A0o();
        C18260x0.A0p(A0V, " AND ", "message_type", " NOT IN ('", A0o5);
        A00(A0o5);
        A0o5.append(15);
        A0o5.append("', '");
        A0o5.append(19);
        A0o5.append("') AND ");
        A08 = AnonymousClass000.A0U("from_me = 1", " ORDER BY sort_id DESC", " LIMIT ?", A0o5);
        String A0X = AnonymousClass000.A0X("(message_type != '8')", AnonymousClass000.A0m(A0V, " AND "));
        StringBuilder A0m2 = AnonymousClass000.A0m(A0X, " AND ");
        A0m2.append("_id >= ?");
        A0B = AnonymousClass000.A0X(" ORDER BY _id ASC", A0m2);
        StringBuilder A0l2 = AnonymousClass000.A0l(A0X);
        A0l2.append(" ORDER BY ");
        A0A = AnonymousClass000.A0V("sort_id DESC", " LIMIT ?", A0l2);
        StringBuilder A0o6 = AnonymousClass001.A0o();
        AnonymousClass001.A1K("   SELECT ", str, ", ", A0o6);
        C18260x0.A0p("chat_row_id", " FROM ", "available_message_view", " WHERE ", A0o6);
        A0o6.append("_id >= ? ");
        A0o6.append(" AND ");
        A0o6.append("_id < ? ");
        A0o6.append(" AND (view_mode IS NULL OR view_mode = 0) ");
        A0o6.append(" AND (expire_timestamp IS NULL OR expire_timestamp >= ? OR keep_in_chat = 1) ");
        A0o6.append(" ORDER BY _id DESC");
        A0L = AnonymousClass000.A0X(" LIMIT ? ", A0o6);
        StringBuilder A0B2 = C18260x0.A0B("   SELECT ", str, ", ", "chat_row_id", " FROM ");
        A0B2.append("available_message_view");
        A0B2.append(" WHERE ");
        A0B2.append("_id > ? ");
        A0B2.append(" AND ");
        C18260x0.A0p("_id <= ? ", " AND (expire_timestamp IS NULL OR expire_timestamp >= ? OR keep_in_chat = 1) ", " ORDER BY _id ASC", " LIMIT ? ", A0B2);
        A0J = A0B2.toString();
        StringBuilder A0B3 = C18260x0.A0B("SELECT ", str, " FROM ", "available_message_view", " WHERE ");
        A0B3.append("chat_row_id = ?");
        A0B3.append(" AND ");
        A0B3.append("starred = 1");
        A0B3.append(" AND ");
        A02 = AnonymousClass000.A0T(AnonymousClass000.A0X("(message_type != '7')", A0B3), " ORDER BY sort_id DESC");
        A03 = AnonymousClass000.A0T(AnonymousClass000.A0U("starred = 1", " AND ", "(message_type != '7')", C18260x0.A0B("SELECT ", str, " FROM ", "available_message_view", " WHERE ")), " ORDER BY timestamp DESC");
        StringBuilder A0B4 = C18260x0.A0B("SELECT ", str, " FROM ", "available_message_view", " WHERE ");
        A0B4.append("chat_row_id = ?");
        A0B4.append(" AND ");
        A01 = AnonymousClass000.A0T(AnonymousClass000.A0X("_id IN (SELECT message_row_id FROM message_ephemeral WHERE keep_in_chat = 1)", A0B4), " ORDER BY sort_id DESC");
        A0C = AnonymousClass000.A0X("_id = ?", C18260x0.A0B("SELECT ", str, " FROM ", "available_message_view", " WHERE "));
        StringBuilder A0B5 = C18260x0.A0B("SELECT ", str, " FROM ", "available_message_view", " WHERE ");
        AnonymousClass001.A1K("chat_row_id = ? AND ", "_id <= ? ", " AND (view_mode IS NULL OR view_mode = 0) ", A0B5);
        A0B5.append(" ORDER BY _id DESC ");
        A0D = AnonymousClass000.A0X("LIMIT 1", A0B5);
        A0F = AnonymousClass000.A0X("sort_id = ?", C18260x0.A0B("SELECT ", str, " FROM ", "available_message_view", " WHERE "));
        A0E = AnonymousClass000.A0U("sort_id = ?", " AND ", "chat_row_id = ?", C18260x0.A0B("SELECT ", str, " FROM ", "available_message_view", " WHERE "));
        StringBuilder A0B6 = C18260x0.A0B("SELECT ", str, " FROM ", "available_message_view", " WHERE ");
        A0B6.append("chat_row_id = ?");
        A0B6.append(" ORDER BY sort_id DESC");
        A0I = AnonymousClass000.A0X(" LIMIT 1", A0B6);
        StringBuilder A0B7 = C18260x0.A0B("SELECT ", str, " FROM ", "available_message_view", " WHERE ");
        A0B7.append("chat_row_id = ?");
        A0B7.append(" AND ");
        A0G = AnonymousClass000.A0U("message_type NOT IN ('8', '10', '90', '12') ", " ORDER BY sort_id DESC", " LIMIT ?", A0B7);
        StringBuilder A0B8 = C18260x0.A0B("SELECT ", str, " FROM ", "available_message_view", " WHERE ");
        A0B8.append("message_type IN ('9' , '26' )");
        A0B8.append(" AND ");
        C18260x0.A0p("origin != 7", " AND ", "chat_row_id = ?", " ORDER BY sort_id DESC", A0B8);
        A04 = A0B8.toString();
        A0H = AnonymousClass000.A0V("message_type = 12", " ORDER BY _id", C18260x0.A0B("SELECT ", str, " FROM ", "available_message_view", " WHERE "));
        StringBuilder A0B9 = C18260x0.A0B("SELECT ", str, " FROM ", "available_message_view", " WHERE ");
        A0B9.append("from_me = 1");
        A0B9.append(" AND ");
        A0B9.append("status < 4");
        A0B9.append(" AND ");
        A0B9.append("_id > ?");
        A0B9.append(" AND ");
        A0M = AnonymousClass000.A0V("sort_id > 0", " ORDER BY _id ASC", A0B9);
    }

    public static void A00(StringBuilder sb) {
        sb.append(8);
        sb.append("', '");
        sb.append(10);
        sb.append("', '");
        sb.append(7);
        sb.append("', '");
    }
}
