package X;

import java.util.Set;

/* renamed from: X.4Th  reason: invalid class name and case insensitive filesystem */
public class C87534Th extends AnonymousClass08Y {
    public final /* synthetic */ AnonymousClass5W6 A00;
    public final /* synthetic */ C110625gl A01;

    public C87534Th(AnonymousClass5W6 r1, C110625gl r2) {
        this.A01 = r2;
        this.A00 = r1;
    }

    public C05550Ty A02(AnonymousClass0XV r6, Class cls, String str) {
        C103355Mo r3 = new C103355Mo();
        AnonymousClass5W6 r0 = this.A00;
        r6.getClass();
        r0.A00 = r6;
        r0.A01 = r3;
        C88874aw r4 = (C88874aw) ((C116845qx) AnonymousClass29x.A00(C116845qx.class, new C88874aw(r6, r0.A02, r0.A03)));
        C160667o6 builderWithExpectedSize = AnonymousClass8OQ.builderWithExpectedSize(152);
        builderWithExpectedSize.put("com.whatsapp.calling.chatmessages.AdhocParticipantBottomSheetViewModel", r4.A00);
        builderWithExpectedSize.put("com.whatsapp.status.advertise.AdvertiseViewModel", r4.A01);
        builderWithExpectedSize.put("com.whatsapp.qrcode.AgentDeviceLoginViewModel", r4.A02);
        builderWithExpectedSize.put("com.whatsapp.conversationslist.ArchiveHeaderViewModel", r4.A03);
        builderWithExpectedSize.put("com.whatsapp.calling.lightweightcalling.viewmodel.AudioChatBottomSheetViewModel", r4.A04);
        builderWithExpectedSize.put("com.whatsapp.calling.lightweightcalling.viewmodel.AudioChatCallingViewModel", r4.A05);
        builderWithExpectedSize.put("com.whatsapp.expressionstray.avatars.AvatarExpressionsViewModel", r4.A07);
        builderWithExpectedSize.put("com.whatsapp.avatar.home.AvatarHomeViewModel", r4.A0E);
        builderWithExpectedSize.put("com.whatsapp.avatar.profilephoto.AvatarProfilePhotoViewModel", r4.A0F);
        builderWithExpectedSize.put("com.whatsapp.userban.ui.viewmodel.BanAppealViewModel", r4.A0G);
        builderWithExpectedSize.put("com.whatsapp.registration.report.BanReportViewModel", r4.A0I);
        builderWithExpectedSize.put("com.whatsapp.blockbusiness.blockreasonlist.BlockReasonListViewModel", r4.A0L);
        builderWithExpectedSize.put("com.whatsapp.wabloks.ui.bottomsheet.BloksCDSBottomSheetViewModel", r4.A0M);
        builderWithExpectedSize.put("com.whatsapp.bonsai.BonsaiConversationTitleViewModel", r4.A0N);
        builderWithExpectedSize.put("com.whatsapp.bonsai.discovery.BonsaiDiscoveryViewModel", r4.A0O);
        builderWithExpectedSize.put("com.whatsapp.bonsai.prompts.BonsaiPromptsViewModel", r4.A0P);
        builderWithExpectedSize.put("com.whatsapp.bonsai.BonsaiSystemMessageBottomSheetViewModel", r4.A0Q);
        builderWithExpectedSize.put("com.whatsapp.bonsai.chatinfo.BotChatInfoViewModel", r4.A0R);
        builderWithExpectedSize.put("com.whatsapp.bonsai.embodiment.BotEmbodimentViewModel", r4.A0S);
        builderWithExpectedSize.put("com.whatsapp.calling.controls.viewmodel.BottomSheetViewModel", r4.A0T);
        builderWithExpectedSize.put("com.whatsapp.payments.ui.viewmodel.BrazilAddPixKeyViewModel", r4.A0U);
        builderWithExpectedSize.put("com.whatsapp.payments.ui.viewmodel.BrazilAddPixSelectionViewModel", r4.A0V);
        builderWithExpectedSize.put("com.whatsapp.payments.ui.viewmodel.BrazilIncomeCollectionViewModel", r4.A0W);
        builderWithExpectedSize.put("com.whatsapp.payments.ui.viewmodel.BrazilPixKeySettingViewModel", r4.A0X);
        builderWithExpectedSize.put("com.whatsapp.report.BusinessActivityReportViewModel", r4.A0Y);
        builderWithExpectedSize.put("com.whatsapp.businessapisearch.viewmodel.BusinessApiSearchActivityViewModel", r4.A0Z);
        builderWithExpectedSize.put("com.whatsapp.biz.compliance.viewmodel.BusinessComplianceViewModel", r4.A0a);
        builderWithExpectedSize.put("com.whatsapp.businessdirectory.viewmodel.BusinessDirectoryActivityViewModel", r4.A0b);
        builderWithExpectedSize.put("com.whatsapp.businessdirectory.viewmodel.BusinessDirectoryConsumerHomeViewModel", r4.A0c);
        builderWithExpectedSize.put("com.whatsapp.businessdirectory.viewmodel.BusinessDirectoryContextualSearchViewModel", r4.A0d);
        builderWithExpectedSize.put("com.whatsapp.businessdirectory.viewmodel.BusinessDirectoryEducationNuxViewModel", r4.A0e);
        builderWithExpectedSize.put("com.whatsapp.businessdirectory.viewmodel.BusinessDirectoryFrequentContactedViewModel", r4.A0f);
        builderWithExpectedSize.put("com.whatsapp.businessdirectory.viewmodel.BusinessDirectoryPopularApiBusinessesViewModel", r4.A0g);
        builderWithExpectedSize.put("com.whatsapp.community.communityInfo.viewModels.CAGInfoChatLockViewModel", r4.A0h);
        builderWithExpectedSize.put("com.whatsapp.community.communityInfo.CAGInfoViewModel", r4.A0i);
        builderWithExpectedSize.put("com.whatsapp.calling.avatar.viewmodel.CallAvatarViewModel", r4.A0j);
        builderWithExpectedSize.put("com.whatsapp.calling.controls.viewmodel.CallControlButtonsViewModel", r4.A0k);
        builderWithExpectedSize.put("com.whatsapp.calling.callgrid.viewmodel.CallGridViewModel", r4.A0l);
        builderWithExpectedSize.put("com.whatsapp.calling.callheader.viewmodel.CallHeaderViewModel", r4.A0m);
        builderWithExpectedSize.put("com.whatsapp.calling.calllink.viewmodel.CallLinkViewModel", r4.A0n);
        builderWithExpectedSize.put("com.whatsapp.calling.chatmessages.CallLogMessageParticipantBottomSheetViewModel", r4.A0o);
        builderWithExpectedSize.put("com.whatsapp.calling.callrating.viewmodel.CallRatingViewModel", r4.A0p);
        builderWithExpectedSize.put("com.whatsapp.calling.callscreen.viewmodel.CallScreenViewModel", r4.A0q);
        builderWithExpectedSize.put("com.whatsapp.contact.picker.viewmodels.CallSuggestionsViewModel", r4.A0r);
        builderWithExpectedSize.put("com.whatsapp.calling.callhistory.viewmodel.CallsHistoryFragmentV2ViewModel", r4.A0s);
        builderWithExpectedSize.put("com.whatsapp.catalogcategory.view.viewmodel.CatalogAllCategoryViewModel", r4.A0t);
        builderWithExpectedSize.put("com.whatsapp.catalogcategory.view.viewmodel.CatalogCategoryGroupsViewModel", r4.A0u);
        builderWithExpectedSize.put("com.whatsapp.catalogcategory.view.viewmodel.CatalogCategoryTabsViewModel", r4.A0v);
        builderWithExpectedSize.put("com.whatsapp.catalogsearch.view.viewmodel.CatalogSearchViewModel", r4.A0w);
        builderWithExpectedSize.put("com.whatsapp.chatlock.ChatLockAuthViewModel", r4.A0x);
        builderWithExpectedSize.put("com.whatsapp.migration.transfer.ui.ChatTransferViewModel", r4.A0y);
        builderWithExpectedSize.put("com.whatsapp.authgraphql.ui.CommonViewModel", r4.A0z);
        builderWithExpectedSize.put("com.whatsapp.community.communitysettings.viewmodel.CommunitySettingsViewModel", r4.A10);
        builderWithExpectedSize.put("com.whatsapp.companionmode.registration.CompanionRegistrationViewModel", r4.A11);
        builderWithExpectedSize.put("com.whatsapp.biz.product.viewmodel.ComplianceInfoViewModel", r4.A12);
        builderWithExpectedSize.put("com.whatsapp.datasharingdisclosure.ui.ConsumerDisclosureViewModel", r4.A14);
        builderWithExpectedSize.put("com.whatsapp.inappsupport.ui.ContactUsWithAiViewModel", r4.A15);
        builderWithExpectedSize.put("com.whatsapp.community.ConversationCommunityViewModel", r4.A16);
        builderWithExpectedSize.put("com.whatsapp.conversation.viewmodel.ConversationSearchViewModel", r4.A17);
        builderWithExpectedSize.put("com.whatsapp.conversation.viewmodel.ConversationTitleViewModel", r4.A18);
        builderWithExpectedSize.put("com.whatsapp.countrygating.viewmodel.CountryGatingViewModel", r4.A19);
        builderWithExpectedSize.put("com.whatsapp.countries.CountryListViewModel", r4.A1A);
        builderWithExpectedSize.put("com.whatsapp.status.crossposting.CrossPostingUpdatesViewModel", r4.A1B);
        builderWithExpectedSize.put("com.whatsapp.status.advertise.CtwaStatusUpsellBottomSheetTriggerViewModel", r4.A1C);
        builderWithExpectedSize.put("com.whatsapp.expressionstray.emoji.EmojiExpressionsViewModel", r4.A1E);
        builderWithExpectedSize.put("com.whatsapp.backup.encryptedbackup.EncBackupViewModel", r4.A1F);
        builderWithExpectedSize.put("com.whatsapp.product.newsletterenforcements.enforcedmessages.EnforcedMessagesViewModel", r4.A1G);
        builderWithExpectedSize.put("com.whatsapp.migration.export.ui.ExportMigrationViewModel", r4.A1H);
        builderWithExpectedSize.put("com.whatsapp.expressionstray.conversation.ExpressionsKeyboardViewModel", r4.A1I);
        builderWithExpectedSize.put("com.whatsapp.expressionstray.ExpressionsSearchViewModel", r4.A1J);
        builderWithExpectedSize.put("com.whatsapp.extensions.phoenix.viewmodel.ExtensionsFooterViewModel", r4.A1K);
        builderWithExpectedSize.put("com.whatsapp.wabloks.base.GenericBkLayoutViewModelWithReload", r4.A1p);
        builderWithExpectedSize.put("com.whatsapp.wabloks.base.GenericBkLayoutViewModel", r4.A1o);
        builderWithExpectedSize.put("com.whatsapp.expressionstray.gifs.GifExpressionsSearchViewModel", r4.A1s);
        builderWithExpectedSize.put("com.whatsapp.backup.google.viewmodel.GoogleDriveNewUserSetupViewModel", r4.A1t);
        builderWithExpectedSize.put("com.whatsapp.migration.android.view.GoogleMigrateImporterViewModel", r4.A1u);
        builderWithExpectedSize.put("com.whatsapp.calling.callhistory.group.GroupCallParticipantSuggestionsViewModel", r4.A1v);
        builderWithExpectedSize.put("com.whatsapp.calling.psa.viewmodel.GroupCallPsaViewModel", r4.A1w);
        builderWithExpectedSize.put("com.whatsapp.group.HistorySettingViewModel", r4.A1x);
        builderWithExpectedSize.put("com.whatsapp.home.HomeViewModel", r4.A1y);
        builderWithExpectedSize.put("com.whatsapp.inappbugreporting.InAppBugReportingViewModel", r4.A1z);
        builderWithExpectedSize.put("com.whatsapp.calling.callgrid.viewmodel.InCallBannerViewModel", r4.A20);
        builderWithExpectedSize.put("com.whatsapp.payments.ui.viewmodel.IndiaPaymentSettingsViewModel", r4.A21);
        builderWithExpectedSize.put("com.whatsapp.payments.ui.international.IndiaUpiInternationalActivationViewModel", r4.A22);
        builderWithExpectedSize.put("com.whatsapp.payments.ui.international.IndiaUpiInternationalValidateQrViewModel", r4.A23);
        builderWithExpectedSize.put("com.whatsapp.payments.ui.viewmodel.IndiaUpiMandateHistoryViewModel", r4.A24);
        builderWithExpectedSize.put("com.whatsapp.payments.ui.mapper.register.IndiaUpiMapperLinkViewModel", r4.A25);
        builderWithExpectedSize.put("com.whatsapp.payments.ui.viewmodel.IndiaUpiNumberSettingsViewModel", r4.A26);
        builderWithExpectedSize.put("com.whatsapp.payments.ui.viewmodel.IndiaUpiPauseMandateViewModel", r4.A27);
        builderWithExpectedSize.put("com.whatsapp.payments.ui.viewmodel.IndiaUpiPaymentTransactionConfirmationBottomSheetViewModel", r4.A28);
        builderWithExpectedSize.put("com.whatsapp.payments.viewmodel.IndiaUpiSecureQrCodeViewModel", r4.A29);
        builderWithExpectedSize.put("com.whatsapp.conversationslist.InteropViewModel", r4.A2A);
        builderWithExpectedSize.put("com.whatsapp.contact.picker.viewmodels.InviteNonWhatsAppContactPickerViewModel", r4.A2B);
        builderWithExpectedSize.put("com.whatsapp.companiondevice.LinkedDeviceEditDeviceViewModel", r4.A2C);
        builderWithExpectedSize.put("com.whatsapp.companiondevice.LinkedDeviceEnterNicknameViewModel", r4.A2D);
        builderWithExpectedSize.put("com.whatsapp.companiondevice.LinkedDevicesSharedViewModel", r4.A2E);
        builderWithExpectedSize.put("com.whatsapp.companiondevice.LinkedDevicesViewModel", r4.A2F);
        builderWithExpectedSize.put("com.whatsapp.businessdirectory.viewmodel.LocationOptionPickerViewModel", r4.A2G);
        builderWithExpectedSize.put("com.whatsapp.calling.callgrid.viewmodel.MenuBottomSheetViewModel", r4.A2H);
        builderWithExpectedSize.put("com.whatsapp.conversation.conversationrow.message.MessageDetailsViewModel", r4.A2I);
        builderWithExpectedSize.put("com.whatsapp.conversation.conversationrow.messagerating.MessageRatingViewModel", r4.A2J);
        builderWithExpectedSize.put("com.whatsapp.conversation.conversationrow.MessageSelectionViewModel", r4.A2K);
        builderWithExpectedSize.put("com.whatsapp.mute.ui.MuteDialogViewModel", r4.A2L);
        builderWithExpectedSize.put("com.whatsapp.registration.accountdefence.NewDeviceConfirmationRegistrationViewModel", r4.A2M);
        builderWithExpectedSize.put("com.whatsapp.product.newsletterenforcements.geosuspend.NewsletterGeosuspensionInfoViewModel", r4.A2N);
        builderWithExpectedSize.put("com.whatsapp.product.integrityappeals.NewsletterRequestReviewViewModel", r4.A2O);
        builderWithExpectedSize.put("com.whatsapp.product.newsletterenforcements.suspension.NewsletterSuspensionInfoViewModel", r4.A2P);
        builderWithExpectedSize.put("com.whatsapp.product.newsletterenforcements.userreports.NewsletterUserReportsViewModel", r4.A2Q);
        builderWithExpectedSize.put("com.whatsapp.biz.order.viewmodel.OrderInfoViewModel", r4.A2R);
        builderWithExpectedSize.put("com.whatsapp.calling.callgrid.viewmodel.OrientationViewModel", r4.A2S);
        builderWithExpectedSize.put("com.whatsapp.calling.controls.viewmodel.ParticipantsListViewModel", r4.A2T);
        builderWithExpectedSize.put("com.whatsapp.payments.ui.viewmodel.PaymentIncentiveViewModel", r4.A2W);
        builderWithExpectedSize.put("com.whatsapp.payments.ui.viewmodel.PaymentMerchantAccountViewModel", r4.A2X);
        builderWithExpectedSize.put("com.whatsapp.pininchat.banner.PinInChatBannerViewModel", r4.A2Y);
        builderWithExpectedSize.put("com.whatsapp.polls.PollCreatorViewModel", r4.A2Z);
        builderWithExpectedSize.put("com.whatsapp.polls.PollResultsViewModel", r4.A2a);
        builderWithExpectedSize.put("com.whatsapp.privacy.disclosure.ui.PrivacyDisclosureContainerViewModel", r4.A2b);
        builderWithExpectedSize.put("com.whatsapp.biz.product.viewmodel.ProductBottomSheetViewModel", r4.A2c);
        builderWithExpectedSize.put("com.whatsapp.quickactionbar.viewmodel.QuickActionBarViewModel", r4.A2e);
        builderWithExpectedSize.put("com.whatsapp.reactions.ReactionsTrayViewModel", r4.A2f);
        builderWithExpectedSize.put("com.whatsapp.pnh.RequestPhoneNumberViewModel", r4.A2g);
        builderWithExpectedSize.put("com.whatsapp.backup.google.viewmodel.RestoreFromBackupViewModel", r4.A2h);
        builderWithExpectedSize.put("com.whatsapp.calling.screenshare.ScreenShareViewModel", r4.A2i);
        builderWithExpectedSize.put("com.whatsapp.expressionstray.stickers.funstickers.viewmodels.SearchFunStickersViewModel", r4.A2j);
        builderWithExpectedSize.put("com.whatsapp.conversation.selection.SelectedImageAlbumViewModel", r4.A2k);
        builderWithExpectedSize.put("com.whatsapp.settings.SettingsAccountViewModel", r4.A2l);
        builderWithExpectedSize.put("com.whatsapp.settings.SettingsChatViewModel", r4.A2m);
        builderWithExpectedSize.put("com.whatsapp.settings.SettingsDataUsageViewModel", r4.A2n);
        builderWithExpectedSize.put("com.whatsapp.backup.google.viewmodel.SettingsGoogleDriveViewModel", r4.A2o);
        builderWithExpectedSize.put("com.whatsapp.settings.SettingsPasskeysViewModel", r4.A2p);
        builderWithExpectedSize.put("com.whatsapp.settings.SettingsPrivacyCameraEffectsViewModel", r4.A2q);
        builderWithExpectedSize.put("com.whatsapp.settings.SettingsSetupUserProxyViewModel", r4.A2r);
        builderWithExpectedSize.put("com.whatsapp.settings.SettingsUserProxyViewModel", r4.A2s);
        builderWithExpectedSize.put("com.whatsapp.conversation.conversationrow.viewmodel.SharePhoneNumberRowViewModel", r4.A2t);
        builderWithExpectedSize.put("com.whatsapp.chatinfo.SharePhoneNumberViewModel", r4.A2u);
        builderWithExpectedSize.put("com.whatsapp.biz.catalog.viewmodel.ShareProductViewModel", r4.A2v);
        builderWithExpectedSize.put("com.whatsapp.shops.ShopsBkLayoutViewModel", r4.A2w);
        builderWithExpectedSize.put("com.whatsapp.shops.ShopsProductPreviewFragmentViewModel", r4.A2x);
        builderWithExpectedSize.put("com.whatsapp.status.archive.StatusArchiveSettingsViewModel", r4.A2y);
        builderWithExpectedSize.put("com.whatsapp.expressionstray.stickers.StickerExpressionsViewModel", r4.A30);
        builderWithExpectedSize.put("com.whatsapp.inappsupport.ui.SupportBkLayoutViewModel", r4.A31);
        builderWithExpectedSize.put("com.whatsapp.conversation.viewmodel.SurveyViewModel", r4.A32);
        builderWithExpectedSize.put("com.whatsapp.tosgating.viewmodel.ToSGatingViewModel", r4.A33);
        builderWithExpectedSize.put("com.whatsapp.calling.schedulecall.upcomingcalls.viewmodel.UpcomingActivityViewModel", r4.A34);
        builderWithExpectedSize.put("com.whatsapp.status.advertise.UpdatesAdvertiseViewModel", r4.A35);
        builderWithExpectedSize.put("com.whatsapp.profile.UsernameViewModel", r4.A37);
        builderWithExpectedSize.put("com.whatsapp.biz.catalog.view.variants.VariantsCarouselFragmentViewModel", r4.A38);
        builderWithExpectedSize.put("com.whatsapp.calling.callgrid.viewmodel.VoiceChatGridViewModel", r4.A39);
        builderWithExpectedSize.put("com.whatsapp.wabloks.commerce.ui.viewmodel.WaBkExtensionsLayoutViewModel", r4.A3A);
        builderWithExpectedSize.put("com.whatsapp.extensions.bloks.viewmodel.WaExtensionsNavBarViewModel", r4.A3B);
        builderWithExpectedSize.put("com.whatsapp.extensions.bloks.viewmodel.WaFlowsViewModel", r4.A3C);
        builderWithExpectedSize.put("com.whatsapp.waffle.wfac.ui.WfacBanViewModel", r4.A3D);
        AnonymousClass8OQ build = builderWithExpectedSize.build();
        String name = cls.getName();
        AnonymousClass4C1 r02 = (AnonymousClass4C1) build.get(name);
        if (r02 != null) {
            C05550Ty r2 = (C05550Ty) r02.get();
            AnonymousClass6C4 r03 = new AnonymousClass6C4(r3, 1);
            Set set = r2.A01;
            synchronized (set) {
                set.add(r03);
            }
            return r2;
        }
        StringBuilder A0o = AnonymousClass001.A0o();
        A0o.append("Expected the @HiltViewModel-annotated class '");
        A0o.append(name);
        throw AnonymousClass000.A0I("' to be available in the multi-binding of @HiltViewModelMap but none was found.", A0o);
    }
}
