package X;

/* renamed from: X.4yr  reason: invalid class name and case insensitive filesystem */
public final class C97624yr extends C101805Ge {
    public static final C97624yr A00 = new C97624yr();

    public C97624yr() {
        super("WA_UNIT_TEST", "DEBUG_TOOL", "XFAM_CROSSPOSTING_NATIVE_AUTH_TOKEN_XCHANGE_GQL", "XFAM_CROSSPOSTING_FB_ACCOUNT_CACHE", "XFAM_CROSSPOSTING_DB_SQL", "XFAM_CROSSPOSTING_ELIGIBILITY_GQL", "XFAM_CROSSPOSTING_NATIVE_AUTH_UI", "XFAM_CROSSPOSTING_REQUEST_GQL", "XFAM_CROSSPOSTING_REQUEST_MANAGER", "XFAM_CROSSPOSTING_WEB_AUTH_PROFILE_DATA_FETCH_GQL", "XFAM_CROSSPOSTING_NATIVE_AUTH_PROFILE_DATA_FETCH_GQL", "XFAM_CROSSPOSTING_STATUS_PRIVACY_UI", "XFAM_CROSSPOSTING_UNLINKING_GRAPH_API");
    }
}
