package X;

/* renamed from: X.58l  reason: invalid class name and case insensitive filesystem */
public enum C998558l {
    PROBLEM_OTHER,
    PROBLEM_AUDIO_NOT_CLEAR,
    PROBLEM_AUDIO_ROBOTIC_OR_DISTORTED,
    PROBLEM_AUDIO_ECHO,
    PROBLEM_AUDIO_TOO_SLOW,
    PROBLEM_AUDIO_OTHERS_COULD_NOT_HEAR_ME,
    PROBLEM_AUDIO_I_COULD_NOT_HEAR_OTHERS,
    PROBLEM_AUDIO_BACKGROUND_OR_CRACKLING_NOISES,
    PROBLEM_VIDEO_FROZE,
    PROBLEM_VIDEO_BLURRY,
    PROBLEM_VIDEO_I_COULD_NOT_SEE_OTHERS,
    PROBLEM_VIDEO_OTHERS_COULD_NOT_SEE_ME,
    PROBLEM_VIDEO_AND_AUDIO_NOT_MATCHING,
    PROBLEM_VIDEO_DISTORTED,
    PROBLEM_OTHER_CALL_KEPT_DISCONNECTING,
    PROBLEM_OTHER_CALL_SUDDENLY_ENDED,
    PROBLEM_OTHER_COULD_NOT_ANSWER_CALL;

    /* access modifiers changed from: public */
    static {
        C998558l[] r3;
        A00 = C73653fr.A00(r3);
    }
}
