package X;

/* renamed from: X.58p  reason: invalid class name and case insensitive filesystem */
public enum C998958p {
    YES,
    YES_WITH_CODE,
    OK,
    ERROR_FAIL_TO_INITIALIZE_WAMSYS,
    ERROR_UNSPECIFIED,
    ERROR_CONNECTIVITY,
    ERROR_TOO_RECENT,
    ERROR_TOO_MANY,
    ERROR_OLD_VERSION,
    ERROR_TEMPORARILY_UNAVAILABLE,
    ERROR_NEXT_METHOD,
    ERROR_TOO_MANY_GUESSES,
    ERROR_BLOCKED,
    ERROR_BAD_PARAMETER,
    ERROR_MISSING_PARAMETER,
    ERROR_PROVIDER_TIMEOUT,
    ERROR_PROVIDER_UNROUTABLE,
    ERROR_BAD_TOKEN,
    ERROR_TOO_MANY_ALL_METHODS,
    ERROR_NO_ROUTES,
    ERROR_INVALID_SKEY_SIGNATURE,
    SECURITY_CODE,
    ERROR_LIMITED_RELEASE,
    ERROR_FLASH_CALL_DISABLED,
    ERROR_DEVICE_CONFIRM_OR_SECOND_OTP,
    ERROR_SECOND_OTP,
    ERROR_NOT_ALLOWED,
    ERROR_CODE_CHECKPOINT,
    ERROR_SEND_SMS_TO_WA,
    ERROR_PROFILE_CHECKPONT,
    ERROR_WAITING_FOR_SMS;

    /* access modifiers changed from: public */
    static {
        C998958p[] r4;
        A00 = C73653fr.A00(r4);
    }
}
